### ISSUE TITLE
Doesn't work in Angular 5

### ISSUE THREAD

**Issue by maxkorz** [Ks89/angular-modal-gallery#101]
## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
I get warnings during compilation and errors in runtime:

<img src="https://i.imgur.com/P8RdbIS.png">

## Steps to reproduce
1. Install the latest Angular CLI (1.5.0)
2. Create a new project:
`ng new bugTest --skip-commit --skip-git --skip-tests --style scss && cd bugTest`
3. Install angular-modal-gallery:
`npm i --save angular-modal-gallery hammerjs mousetrap @types/hammerjs @types/mousetrap`
4. Replace contents of app.module.ts with 
```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

import 'hammerjs';
import 'mousetrap';
import { ModalGalleryModule } from 'angular-modal-gallery';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    ModalGalleryModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
5. do `ng serve` and open http://localhost:4200/ in browser

## Environment
```
Angular CLI: 1.5.0
Node: 8.5.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by Ks89** [comment]
Mmm.. Ok I'll try tomorrow. 
I'm working on a new major release build with angular 5 and it is working very well with 5.0.0. So, don't be scared ;). 
If necessary, I'll refactor the existing version (3.x.x) copying the structure of the next major release to support angular 5. 
I'll confirm for sure in one or two days.

**Comment by Ks89** [comment]
I confirm this bug. I'll try to fix during this weekend.

**Comment by Ks89** [comment]
I fixed this issue.
I'll release angular-modal-gallery 3.4.0 with official Angular 5 support in one or two days as promised.
I'll also release this library with official [Angular Package Format v4.0](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) support 👍

**Comment by Ks89** [comment]
@maxkorz 4.0.0-rc.1 with Angular 5 support is available here https://github.com/Ks89/angular-modal-gallery/releases/tag/v4.0.0-rc.1

To install run: `npm run install angular-modal-gallery@beta`

The final version will be released tomorrow.

Let me know if everything is ok with this new beta version.

thank u.

**Comment by Ks89** [comment]
I have a working implementation of 4.0.0, but there is a bug in angular-cli. I'm waiting for this https://github.com/angular/angular-cli/issues/8318

**Comment by maxkorz** [comment]
@Ks89 I installed `angular-modal-gallery@beta` and I'm getting the following error on compilation:
```
ERROR in Error: Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supported.
Consider replacing the function or lambda with a reference to an exported function,
resolving symbol ɵa in /node_modules/angular-modal-gallery/angular-modal-gallery.d.ts,
resolving symbol ModalGalleryModule.forRoot in /node_modules/angular-modal-gallery/angular-modal-gallery.d.ts,
resolving symbol AppModule in /src/app/app.module.ts,
resolving symbol AppModule in /src/app/app.module.ts
```

**Comment by Ks89** [comment]
Thank u for reporting that.
Did you try to remove your node_modules, package-lock.json and all temp folders and run `npm install` again?

I saw this problem some months ago [here](https://github.com/qdouble/angular-webpack2-starter/) and the only way to fix was to use yarn. I never understood the reason.

I hope that felipesilva will help me, because I cannot release 4.0.0 with all these problems. probably I should wait for Angular 5.0.1 and angular-cli 1.5.1 hoping that many bugs will be fixed.
When felipesilva will answer I'll update this issue again.

**Comment by maxkorz** [comment]
@Ks89 oops. I got the above error with `ng serve --aot`. When I use `ng serve` I get the same errors and warning as in my first message.

Log after compilation:
```
WARNING in ./node_modules/angular-modal-gallery/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Work\Work\futureapp\frontend\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Work\Work\futureapp\frontend\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Work\Work\futureapp\frontend\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Work\Work\futureapp\frontend\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Work\Work\futureapp\frontend\node_modules\tapable\lib\Tapable.js:289:11
    at C:\Work\Work\futureapp\frontend\node_modules\html-webpack-plugin\index.js:60:9
    at tryCatcher (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
 @ ./node_modules/angular-modal-gallery/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular-modal-gallery/angular-modal-gallery.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/angular-modal-gallery/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Work\Work\futureapp\frontend\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Work\Work\futureapp\frontend\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Work\Work\futureapp\frontend\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Work\Work\futureapp\frontend\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Work\Work\futureapp\frontend\node_modules\tapable\lib\Tapable.js:289:11
    at C:\Work\Work\futureapp\frontend\node_modules\html-webpack-plugin\index.js:60:9
    at tryCatcher (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Work\Work\futureapp\frontend\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
 @ ./node_modules/angular-modal-gallery/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular-modal-gallery/angular-modal-gallery.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

I use over 20 npm modules alongside with your module, and only your module has such problems, so it has to be something specific. I'll look into it and try to help

**Comment by maxkorz** [comment]
I removed my node_modules folder as you suggested and that error is gone. Now I'm getting `staticSymbol.assertNoMembers is not a function`

**Comment by Ks89** [comment]
@maxkorz ok still not perfect, but at least there aren't errors like `ERROR in Error: Error encountered resolving symbol values statically` again. I really hate that error.

I know that it is crazy, but please could you try to replace your /node_modules/angular-modal-gallery/ files and folders with the content of the zip attached?

[angular-modal-gallery-4.0.0-rc.2.zip](https://github.com/Ks89/angular-modal-gallery/files/1443350/angular-modal-gallery-4.0.0-rc.2.zip)

**Comment by maxkorz** [comment]
@Ks89 I cloned your repo, switched branch to "develop", and executed these commands:
1. npm install
2. npm run build:lib

Then I copied files from `dist` folder to `/my-project/node_modules/angular-modal-gallery`.

And all the errors and warning have disappeared! `ng serve` works (with `--aot` too) and the plugin works perfectly.

Then I removed copied files and executed `npm i angular-modal-gallery@beta` and the error has returned.

After that I opened `/node_modules/angular-modal-gallery/package.json` to see which version was installed. Turns out NPM installs `  "version": "3.4.0-rc.1"`, while `develop` branch is `  "version": "4.0.0",`
https://github.com/Ks89/angular-modal-gallery/blob/develop/package.json#L3

Maybe that's the problem?

Also, for some reason your package creates `node_modules` folder inside the package: https://i.imgur.com/jOlOUx2.png

**Comment by maxkorz** [comment]
@Ks89 yes, seems like code in angular-modal-gallery-4.0.0-rc.2.zip works fine, I just tested it.

**Comment by Ks89** [comment]
Perfect, but I don't know why before wasn't working and now yes.

I'll do some other experiments.

**Comment by maxkorz** [comment]
@Ks89 maybe it doesn't work because you have angular in dependencies?
https://github.com/Ks89/angular-modal-gallery/blob/develop/package.json
```json
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.5.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "mousetrap": "^1.6.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.18"
  },
```

And when I do `npm install`, npm installs a copy of angular inside our package and that causes all the errors...?

**Comment by maxkorz** [comment]
Yes, looks like it. I copied content of angular-modal-gallery-4.0.0-rc.2.zip to `/my-project/node_modules/angular-modal-gallery`, then I executed `npm install` inside that directory. After that `Error encountered resolving symbol values statically` error is back

**Comment by maxkorz** [comment]
Take a look at [angular-library-seed](https://github.com/trekhleb/angular-library-seed/blob/master/package.json). Looks like everything has to be in devDependencies

**Comment by Ks89** [comment]
mmm It's possibile. I'll investigate.

When you type `npm install` the remote version will be downloaded again and the local content will be removed, so to test it again I have to compile rc.2 without dependencies but with devDependencies.

**Comment by Ks89** [comment]
Removing both devDependencies and dependencies and test it with npm link it seems working.
I'll push rc.2 in a couple of hours.

**Comment by Ks89** [comment]
@maxkorz 
please try again with rc2 running `npm i --save angular-modal-gallery@experimental`

**Comment by maxkorz** [comment]
@Ks89 it works. No errors or warnings.

**Comment by Ks89** [comment]
oh yes. perfect
thank you for your support. I'll push 4.0.0 final.

I'll also add your nickname to the changelog with a special thanks 👍 

Issue closed
