### ISSUE TITLE
Attach to Body, or as high in the DOM as possible

### ISSUE THREAD

**Issue by pavilionweb** [Ks89/angular-modal-gallery#111]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

The overlay gets added inside the gallery component, but there's some other components that are rendered on top of the overlay, in particular flex based components

## Expected behavior

The overlay should be the first element in the HTML if possible, so no need to fiddle with z-indexes or anything.

## Environment

<pre><code>
- Node version: XX  
- npm version: XX  
- Platform:  
- Angular version: X.Y.Z
-

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
I never though about this, but It could be a good idea.
What are you trying to say is that I should attach the css class with semi-transparent background directly to the body tag of the document instead of a <div>?

**Comment by wenzirang** [comment]
I have this problem, too

**Comment by Ks89** [comment]
Please could you explain me why this is a problem? Could you give me a scenario (if you want also on jsbin or plnkr.co)?

I tried to work on this, but changing the current behaviour created lot of issues.

I need a solution that shows a background over everything (also over things with really high zindex, as navbar in bootstrap 4).

**Comment by majorbenks** [comment]
I have the same problem. It e.g. occurs when I place the gallery inside a css grid (display: grid).

**Comment by domiSchenk** [comment]
This could solve the problem with issue #95.
If its appended to body all the grid:css and modals do not block the gallery.

**Comment by Ks89** [comment]
I'll investigate again in August, because I'm completely full until the beginning of August.
PS: if you have a resource or other stuff to do this, please share it.

**Comment by domiSchenk** [comment]
Other libraries are using` @angular/cdk/overlay` to archive this.

**Comment by Ks89** [comment]
Interesting, I'll investigate a bit next week. thank you.

**Comment by luisCortes** [comment]
Hello, do you have any update on this, I'm having the same problem, the preview of an image is shown inside a component and not over the whole screen viewport.

![image](https://user-images.githubusercontent.com/18152434/44169316-a0062d80-a099-11e8-872a-0b3e1eeda125.png)

**Comment by luisCortes** [comment]
Another issue is that I can still use the scroll behind the overlay, here's an image of that:

![image](https://user-images.githubusercontent.com/18152434/44169434-0a1ed280-a09a-11e8-9096-cb8b653d434d.png)

**Comment by Ks89** [comment]
sorry, no news at the moment

**Comment by Ks89** [comment]
@domiSchenk can you share the name of some of those libraries to see how they are using cdk? Thank u.

**Comment by luisCortes** [comment]
Thank you @Ks89

**Comment by Ks89** [comment]
Fully implemented (branch `800`) and scheduled for 8.0.0-beta.1 that is coming soon.

I close this issue because already done and It will be available in a beta release in some days.
