### ISSUE TITLE
buttonsConfig Icon change

### ISSUE THREAD

**Issue by Iamguy84** [Ks89/angular-modal-gallery#114]
Hi,
 
I want to change the icon e.g fa fa-close because I am using Primeng without font awesome.
Is It possible?
I am waiting for your response.

Thanks

**Comment by Ks89** [comment]
Hi.

Right now with version 4.x.x is not possibile, however the latest public alpha of 5.0.0 has this feature.

The release date is about the end of February.

If you want,  you can check the related issue with a working demo on plunker

**Comment by Iamguy84** [comment]
Thank you for quick response.
I cannot wait for next final 5.0.0 version. :)

**Comment by Ks89** [comment]
Thank for your interest.

I close this issue because it's already implemented in 5.0.0 alpha.

I suggest you to subscribe to all notifications of issue #80 to be always up to date
