### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by sander1693** [Ks89/angular-modal-gallery#115]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Expected behavior

Hello. I'd like to ask for a feature that I don't know if the package has it already.
I'm trying to include the gallery in a Datatable where I list products, and each product has some images. I'd like that the datatable only show one prime image and when the user clicks it, the modal gallery opens. But when the user clicks in the image, the component show every thumbnail in the place I call the package, instead of open the gallery directly. My question is if there is a way to skip that step (I don't want the component show the thumbnails).
Thanks for your help. This is my first issue and I'm Spanish, so I'm sorry if I didn't explain myself very well.

## Minimal reproduction of the problem with instructions

In my component I have this function that is called when the user clicks the product image in the datatable. I want the gallery opens when `openModalWindow` gets `true` value.

```
openModalGallery(product) {
	this.images = [];
	product.images.forEach(img => {
		const iFormated = product.images_formated.filter(i => i.id === img.id);
		console.log('IMAGEN FORMATEADA:', iFormated);
		const image = new Image(img.path_image, null, img.description);
		this.images.push(image);
	});
	console.log('IMAGES', this.images);
	this.openModalWindow = true;
	console.log(this.openModalWindow);
}
```

## Environment

<pre><code>
- Node version: 8.9.3  
- npm version: 5.5.1  
- Platform:  Windows
- Angular version: 4.4.6
-

Browser:
- [x] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by sander1693** [comment]
Maybe the component could have an option that opens directly the first image of the images array.

**Comment by Ks89** [comment]
@sander1693  thank u for you interest.
Which version of angular-modal-gallery are you using? 4.x.x or 5.0.0-alpha.x?

I don't know if I understood your problem, but I wanna try to answer.

You said that:
```
But when the user clicks in the image, the component show every thumbnail in the place I call the package, instead of open the gallery directly.
```
This is clearly a wrong behaviour/setup/config. You can show a N number one thumbnails and clicking on it you can show directly modal gallery. Obviously N can be equals to 1.

Check this example (removing '+ more' feature) : https://ks89.github.io/angular-modal-gallery.github.io/demo/array-pointer

PS: also I suggest to check official examples in this repo.

**Comment by sander1693** [comment]
@Ks89 thanks for your answer.
I'm using 4.0.1 version.

I think I wanted a special behaviour, maybe this package isn't made for this. I want that when the user clics an image (this image isn't a thumbnail made by the angular-modal-gallery), a function that creates the images array is called and the gallery opens right to the first image.

I think this could be a good behaviour or feature request. Like in other gallery images, this gallery could be called in the component through a method call:

This method can load the images:
> this.galleryService.load(imagesArray);

And this other opens the gallery:
> this.galleryService.open();

I saw this behaviour in another galleries but I couldn't prove them because they need Angular 5.x.x and my proyect is Angular 4.x.x made.

Thanks for your attention.

**Comment by Ks89** [comment]
@sander1693

> this image isn't a thumbnail made by the angular-modal-gallery

This is something that I don't understand. Why?
You can build a custom thumb gallery with a single image and clicking on it the modal gallery will appear (in a 'modal way')

> the gallery opens right to the first image.

What do you mean?
Would you see an inline gallery behind the thumb or a modal gallery (full screen like now)?
Feel free to upload sketches with paint or something else to explain this idea.

> This method can load the images: this.galleryService.load(imagesArray); And this other opens the gallery: this.galleryService.open();

This is a very good idea, however I cannot implement it with version 5.0.0, otherwise the release date will be in 2056 :) I can schedule this with high priority for this spring (for instance 5.1.0 or 5.2.0)

**Comment by sander1693** [comment]
@Ks89 sorry if I don't explain myself very wel ;).

From the begining I thought the images array won't be created until user clicks on a product image because there are lots of products with some images, and by this way, memory would be overload needlessly.
The problem is there are many products with many photos and info, and I think show every thumbnail would overload the datatable. Maybe the image pointer is a good solution for me.

I'll try to upload something to explain my idea.

Tanks for your help.

**Comment by Ks89** [comment]
Are there any news about that? It's still an issue?

**Comment by Ks89** [comment]
temporary closed. Waiting for updates
