### ISSUE TITLE
suggestion: add loading indicator icon

### ISSUE THREAD

**Issue by yarozar** [Ks89/angular-modal-gallery#120]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When you browse between images in gallery using arrows or even during initial load of full image there is no indication when that image is loading. This can confuse user and he can repeat clicking on arrows, thus skipping image, etc.

## Expected behavior
Would be nice to have some loading indicator icon representing the fact that image is being loaded when user clicks on arrows in gallery.

Thanks for consideration!

**Comment by Ks89** [comment]
Yes I confirm that it's already implemented in 5.0.0 alpha

**Comment by Ks89** [comment]
fixed in rc.1 and released
