### ISSUE TITLE
Support 'fullTemplateTypeCheck'

### ISSUE THREAD

**Issue by Enngage** [Ks89/angular-modal-gallery#122]
Hi, 

Currently compiling your library with [fullTemplateTypeCheck ](https://angular.io/guide/aot-compiler#fulltemplatetypecheck)angular option (introduced very recently) fails with just a few minor issues. 

Could you take a look at those? Currently I can't use the option because of these errors.

**Comment by Ks89** [comment]
Ok. I'll check tomorrow.

Are talking about version 5.0.0 beta?

**Comment by Enngage** [comment]
Yup. Cool :)

**Comment by Ks89** [comment]
I tried but I cannot reproduce this issue.
Are you really really sure that you are using 5.0.0-beta.1? If yes, can you try to use my official example with angular-cli here https://github.com/Ks89/angular-modal-gallery/tree/v4/examples/angular-cli?

**Comment by Enngage** [comment]
After enabling the template check, you need to build the library using
--aot attribute for it to take effect.

Instead of `ng build` use `ng build --aot` and you should see the errors in
console.

**Comment by Ks89** [comment]
@Enngage I cannot reproduce this issue (with --aot).

Please could you get this example https://github.com/Ks89/angular-modal-gallery/tree/v4/examples/angular-cli (install all deps with npm i) and try to build it by yourself? I really don't know what can I do to understand the problem. I suggest to try to compare it with your code.

PS: could you share your log with errors?

**Comment by Enngage** [comment]
I'm seeing following errors with the latest beta-2:

![err](https://user-images.githubusercontent.com/7137351/36315510-35fcf552-1338-11e8-8bfe-3027345a46b1.png)

This seems to be coming from the library so I don't think my code is the problem.

**Comment by Ks89** [comment]
mmm, probably yes, it is 'strictNullChecks'. I'll check this weekend

**Comment by Ks89** [comment]
@Enngage you are right, this happens when you enable 'strictNullChecks'.

However the typescript's error is so ambiguous that It's difficult to understand the problem (this issue https://github.com/Microsoft/TypeScript/issues/8274  should be really closed :)). I need a couple of days to fix this. When I'm ready to close this issue, I'll release RC1.
Thank you for the hint of strictNullChecks.

PS: I'm adding to all tsconfig files of both the lib and the official examples this:
```
"angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "preserveWhiteSpace": false,
    "strictInjectionParameters": true,
    "strictNullChecks": true
  },
```
Do you suggest to add other params to angularCompilerOptions?

**Comment by Ks89** [comment]
Fixed. Simpler than I expected.

I'll release RC1 this evening.

**Comment by Ks89** [comment]
RC1 released right now 👍

**Comment by Enngage** [comment]
Thanks :) I can confirm it works fine now.  As for the CompilerOptions - that seems to be for now.
