### ISSUE TITLE
Image descriptions with html inside

### ISSUE THREAD

**Issue by Ks89** [Ks89/angular-modal-gallery#123]
feature request from #80

**Comment by Ks89** [comment]
already available as 5.1.0-beta.1

**Comment by ckelkar** [comment]
@Ks89 ,
I really appreciate your help

**Comment by Ks89** [comment]
No problem man. This is an open source project for me but also for all of you, so contributions and feature requests are really important to improve the library.

**Comment by Ks89** [comment]
5.1.0 released
