### ISSUE TITLE
Angular 4 app is broken on IE11 

### ISSUE THREAD

**Issue by Hesesses** [Ks89/angular-modal-gallery#126]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

App is broken

## Expected behavior

"everything works"

## Minimal reproduction of the problem with instructions

I'm using Angular 4 and angular-modal-gallery 5.1. The app is broken when using IE11 with
`syntax error on line Class ClickOutsideDirective`

edit. App broken means the screen shows only "loading..." text 

## Environment (the most important section to fill very carefully)

<pre><code>
- Node version: 9.2.1  
- npm version: 5.6.0  
- Operating System and version:  
- Angular version: ^4.0.0 
- angular-cli version (or SystemJS/Webpack): 1.7.2 
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT <- All modes

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
Hi thank u for your report, I'll check this evening.

Did you try if my official examples are working on ie11? 

Did you include all necessary polyfills?

**Comment by Hesesses** [comment]
All examples here: https://ks89.github.io/angular-modal-gallery-2018.github.io/demo seems to work on ie11.

Polyfills? :)

**Comment by Ks89** [comment]
Yes in your polyfills,  did you include for instance web animations? Check my polyfills in one of my official examples.

It's only an idea. I'll check in a better way this evening, however if my website is working I suppose that it isn't a bug.

**Comment by Hesesses** [comment]
```
/** IE10 and IE11 requires the following for NgClass support on SVG elements */
 import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
 import 'web-animations-js';  // Run `npm install --save web-animations-js`.
```
Installed those, but still having the same error. On your examples, everything seems to work. 
Can it be something with Angular 4 as your examples is Angular 5?

**Comment by Ks89** [comment]
Try with webpack example. It's the only one with angular 4. Yes, all the others are with angular 5.

**Comment by Ks89** [comment]
@Hesesses I tried with my `examples/webpack` with Angular 4 and I confirm that it's working without problems.

I suggest to compare your code and my webpack example. If you have something to share (a small demo to reproduce the issue), I'll happy to help you.

**Comment by Hesesses** [comment]
I had few imports from "angular-modal-gallery/angular-modal-gallery" instead of "angular-modal-gallery" 
I blame PhpStorm  🙈 

Thank you very much for creating this awesome plugin 👍
