### ISSUE TITLE
Ability to configure description styling

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [Ks89/angular-modal-gallery#132]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
The image descriptions comes with default styling (i.e. background: rgba(0, 0, 0, 0.5). The styling doesn't fit my design. I can override it with turning ViewEncapsulation off or using the /deep/ structure, but in the light of a full fletched configurable library, you might want to consider a configurable class. 

## Expected behavior
I'd like to influence the css for the description element.

**Comment by tobi-or-not-tobi** [comment]
FYI if #133 is solved, this is less of an issue, however still preferred.

**Comment by Ks89** [comment]
This is a good idea, it was already in my schedule, but I'm happy for the interest about this, so I'll try to improve it in next releases.

**Comment by Ks89** [comment]
same as #133. I implemented also this feature as part of #133, so I close this one.

Released as 5.4.0-beta.1. Final version coming soon.

**Comment by tobi-or-not-tobi** [comment]
Works fine. I just initially expected that I'd be able to override a single property, but once I'm adding, lets say only margin, also bgColor and textColor need to be set. No big deal. 

If user want to set the title on the top, they need a bit more. With the following style rules I'm able to move it up: That would require a position property and height. 

```
    position: absolute;
    background: rgba(0, 0, 0, 0.5);
    color: white;
    top: 0;
    height: 40px;
```

**Comment by Ks89** [comment]
All properties should be optional. Probably it's a. Bug. I'll check it.

You are right, also top, bottom, right, left width, height are useful.
OK, I'll try it.

**Comment by tobi-or-not-tobi** [comment]
Cool, don't forget position :)

**Comment by Ks89** [comment]
beta2 released with all other params.

PS: be careful to change width property, because it's not so simple (probably I should remove it to prevent issues)

If you have other suggestions feel free to speech :)
