### ISSUE TITLE
Support for RxJS 6

### ISSUE THREAD

**Issue by mlc-mlapis** [Ks89/angular-modal-gallery#134]
## Current behavior
Using RxJS 5.5.x imports like `import { Observable } from 'rxjs/Observable';` are used.

## Expected behavior
RxJS 6 brings simplified imports like `import { Observable } from 'rxjs';` ... so it is necessary to import all classes from directly `rxjs`.

## What is the motivation / use case for changing the behavior?
The problem is the size of a bundled application when the application is using RxJS 6 and a package is using 5.5.x because it is necessary to use `rxjs-compat` package and load both of them.

## Other conditions
If all places in code where `angular-modal-gallery` is using RxJS imports are manually rewritten to new RxJS import style, everything works so it seems that this change would be very easy to done and the only question is how to manage and publish this package for RxJS 5.5.x and RxJS 6.x in parallel.

## Environment (the most important section to fill very carefully)
<pre><code>Angular 6.0.0-rc.3
RxJS 6.0.0-tactical-rc.1
</code></pre>

**Comment by Ks89** [comment]
I'm not using rxjs in the sourcecode of the lib right now. I'll add it in the next releases, but for now there aren't imports of rxjs.

Did you find a specific problem?
rxjs 6 is backward compatibile with angular 5?

**Comment by mlc-mlapis** [comment]
@Ks89 ... if you look at `angular-modal-gallery.umd.js` you can see that there is `require('rxjs/Observable')` for example.

There is `rxjs-compat` package for backward complete compatibility ... but in reality for the most of app just updating imports is 99% of the work to switch to RxJS 6.

**Comment by mlc-mlapis** [comment]
@Ks89 ... ah, sorry. You are right. It was really version 4.0.1.

**Comment by Ks89** [comment]
Ok perfect, no problem.
