### ISSUE TITLE
Disable click events on the current image

### ISSUE THREAD

**Issue by iss936** [Ks89/angular-modal-gallery#135]
Is it possible to disable event show,  when there is a click on the currentImage ?
I do not want go to the next image when i click to the currentImage.

thks.

**Comment by Ks89** [comment]
Interesting use case that I didn't implement.
I'll schedule for next releases

**Comment by rezo-evodion** [comment]
I am interested too, I don't want to go to next image when I click  👍

**Comment by Ks89** [comment]
Ok, scheduled for 5.7.0, because I have to release a very challenging feature in 5.6.0 and I need some weeks. Please, be patient

**Comment by Ks89** [comment]
Implemented in branch 'develop'.
I'll merge it with master this weekend and I'll publish 5.7.0 as stable release.
