### ISSUE TITLE
when only one photo, the photo is not centered

### ISSUE THREAD

**Issue by pieterdegraeuwe** [Ks89/angular-modal-gallery#136]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When there is only one photo, the photo is not centered, but left aligned.

## Expected behavior
Photo should be centered

## Minimal reproduction of the problem with instructions
See punker (and click on the firest (and only) photo )
https://plnkr.co/edit/yBu18OCZQQjHPdyR0UGY?p=preview

## Environment (the most important section to fill very carefully)

<pre><code>
- Node version: 6.11.0
- npm version: 3.10.10
- Operating System and version:  Windows 
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [x] Firefox version 59.02
- [x] Edge version 41.16299.248.0
- [x] Opera version 52.0.2871.40

</code></pre>

**Comment by Ks89** [comment]
Probably, I won't fix it this week, because I'm really busy, but I'll try asap. Please be patient.

**Comment by Ks89** [comment]
Sorry for the delay, but I was really busy.
I'll try to fix it this weekend or next week.

**Comment by Ks89** [comment]
Thank you for your patience.
Issue fixed in 5.5.1.

Feel free to re-open if you think that it's not ok.

**Comment by pieterdegraeuwe** [comment]
however this issue is already closed (my fault, sorry for that), I confirm that this issue is indeed fixed !
Thanks for the excellent work !

**Comment by Ks89** [comment]
@pieterdegraeuwe 
thank u and I'm happy that you are happy :).

Feel free to both express your ideas and to contribute.
