### ISSUE TITLE
Gallery does not work in Microsoft Edge

### ISSUE THREAD

**Issue by circy** [Ks89/angular-modal-gallery#145]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Click on image image thumbnail to show gallery (e.g. in the live demo https://stackblitz.com/edit/angular-modal-gallery-v5/), but image is not shown in gallery view

## Expected behavior

Image is shown in big/ gallery view when clicking on it

## Minimal reproduction of the problem with instructions

Open https://stackblitz.com/edit/angular-modal-gallery-v5/ in Edge and click on image

## What is the motivation / use case for changing the behavior?

Should work on all browsers

## Environment (the most important section to fill very carefully)

<pre><code>
https://stackblitz.com/edit/angular-modal-gallery-v5/

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ x] Edge version 42.17134.1.0, EdgeHTML 17.17134

**Comment by Ks89** [comment]
Hi, I fixed this issue in 6.0.2, it still seems a bug of Edge, but I've found a different approach to prevent this bug.

Please could you try the beta version and confirm if it ok before the official release?

Install with: `npm i --save @ks89/angular-modal-gallery@6.0.2-beta.1`

When you will confirm I'll publish the final release of 6.0.2.

Thank u for the support.

**Comment by circy** [comment]
Hello, great. Now it works wonderfully. Thank you :)

**Comment by Ks89** [comment]
Perfect, release as 6.0.2
