### ISSUE TITLE
Fetch images from an external data source

### ISSUE THREAD

**Issue by neethukc** [Ks89/angular-modal-gallery#148]
Hi, 
Can I fetch images from an external data source ?
Is there any way for it ?
If there is can anyone share one example to do the same .

**Comment by Ks89** [comment]
Hi, yes add image urls from your external server, but remember that you won't be able to download it automatically because of browser's restrictions

**Comment by Ks89** [comment]
Hi! Is it enough as answer or do you need more info? Feel free either to comment or close the issue.
