### ISSUE TITLE
Image cover 

### ISSUE THREAD

**Issue by dadrake3** [Ks89/angular-modal-gallery#150]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I have some tall images and the top and bottom portion in the modal view is cropped out, as scene here
https://imgur.com/a/3dzn0wD

## Expected behavior

I heard object-fit: cover should fix this though I am not sure where to add that

## Environment (the most important section to fill very carefully)

<pre><code>
- Node version: 10.4.1  
- npm version: 6.1.0  
- Operating System and version: Mac 
- angular-cli version: 6.0.8 

Browser:
- [X] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by Ks89** [comment]
Hi could you share one of these images to test it? This shouldn't happen and it can be a bug.

**Comment by dadrake3** [comment]
@Ks89 basically I want the images to resize so that the entire image is displayed and not cropped

**Comment by dadrake3** [comment]
I fixed it, had some conflicting css, sorry for the trouble

**Comment by Ks89** [comment]
Ok perfect. Sorry for the delay, I'll back this weekend to fix some issues. This week is completely full xd
