### ISSUE TITLE
Make image change on specific Timestamp

### ISSUE THREAD

**Issue by hn6pot** [Ks89/angular-modal-gallery#152]
Hi, 
is there a way to make image change on specific timestamp ? 
like a slideshow.  

Thanks a lot !

**Comment by Ks89** [comment]
Hi. That feature is not available yet.

I'll add it in future releases but I cannot say a release date it right now.

**Comment by Ks89** [comment]
If you want to contribute and help to implement it feel free to open pull requests.

This summer I have to work on a new major release and Ill add new things with higher priority.

**Comment by Ks89** [comment]
I have another idea. What about a method via galleryservice to change image manually via your component's code?

In future release I'll add it natively, but if you need this feature this summer I can implement it in that way

**Comment by Ks89** [comment]
I'll implement this feature in 7.0.0 (or 7.1.0) that it is already work in progress.

**Comment by Ks89** [comment]
I'm sorry for the delay. 7.0.0 was really challenging. I released the last RC some days ago, so in a couple of weeks I'll release the final version.
7.1.0 with this feature, will be released in December. Please be patient :)

**Comment by Ks89** [comment]
Feature fully implemented and tested (develop branch). Doc website 7.2.0 ready to be published.
This feature will be released as 7.2.0 before the end fo the year. Probably in one or two days.

Issue closed. Feel free to comment if you have problems.
