### ISSUE TITLE
Slider Swipe in Tablet and Mobile

### ISSUE THREAD

**Issue by anacatarinasousaaa** [Ks89/angular-modal-gallery#154]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
In mobile and tablet,  the swipe is inverted: when we swipe left, the slider navigates to the previous slider.

## Expected behavior
When we swipe left, the slider navigates to the next slider, wich is the expected common behavior.

## What is the motivation / use case for changing the behavior?
The most common behavior, wich we would like to have in our website, is that when we swipe left, the slider navigates to the next image and, when we swipe right, the slider navigates to the previous image.

**Comment by Ks89** [comment]
Ok.

I'll add a new config property to invert the sliding in 6.2.0

**Comment by Ks89** [comment]
@anacatarinasousaaa feature implemented (develop branch) and it will be released as 6.2.0 this weekend.
I have to write some unit tests to be sure that everything is ok.

**Comment by Ks89** [comment]
tests completed I'll release 6.2.0 today.

**Comment by Ks89** [comment]
released. Doc website will be updated in today, please be patient.
