### ISSUE TITLE
Infinite Slide Bug If Images Added Asynchronously

### ISSUE THREAD

**Issue by rezo-evodion** [Ks89/angular-modal-gallery#157]
## I'm submitting a...

<pre><code>
[x] Bug report  

</code></pre>

## Current behavior

Hello it's me again. ;)

If images are added after the gallery is already opened with: 
`[slideConfig]="{infinite: true, sidePreviews: {show: false}}"`
the next and previous buttons are not shown.
Please take a look at the stackBlitz demo. 

## Expected behavior

The next and previous buttons are shown if there are two or more images present.

## Minimal reproduction of the problem with instructions

At first there is one image present and the gallery is shown. After a second a second image is added as you can see in the dot preview.
If you then click on the second dot (or the navigation button in the preview) it refreshes as it should.

My official live example on StackBlitz (based on Angular Material Stackblitz Starter) is: https://stackblitz.com/edit/angular-material2-issue-u3uyhd?file=app%2Fapp.component.html

**Comment by Ks89** [comment]
Issue confirmed

**Comment by Ks89** [comment]
@rezo-evodion released as 6.2.2-beta.1. It should be ok, but I have some problems with unit testing, so I released this issue asa beta, at the moment. Fell free to use it, I won't change anything in the final version.

**Comment by Ks89** [comment]
6.2.2 final released

feel free to re-open if you find something wrong

**Comment by rezo-evodion** [comment]
hello, 
it works perfect now, thanks +1
