### ISSUE TITLE
Back button with modal opened freeze the page scroll

### ISSUE THREAD

**Issue by srtab** [Ks89/angular-modal-gallery#159]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

When you click a back button with the modal gallery opened, the page scroll freeze. This is happening due a attribute added to the body _style="overflow: hidden;"_ and changing the page this is not reset.

## Expected behavior

The page scroll naturally as expected.

## Minimal reproduction of the problem with instructions

Using the available project demo, open a modal gallery and then click the back button of the browser.

**Comment by Ks89** [comment]
Hi
Is it happening on smartphones or also on desktops?

**Comment by srtab** [comment]
I tested in desktop, Firefox and Chrome, and in smartphones, Safari iPhone. I was able to reproduce the problem only on desktops. I don't have a Android phone to test, but i believe it's happening the same problem.

**Comment by Ks89** [comment]
Issue confirmed. I'll try to fix it this weekend

**Comment by Ks89** [comment]
@srtab I fixed the issue. I'll release 6.2.3 this weekend as promised.
I want to do some tests on different browsers and with SSR before to release it.

Thank u for the issue, I missed completely this bug.

**Comment by srtab** [comment]
Ok @Ks89, many thanks for the fast response and resolution!!

**Comment by Ks89** [comment]
6.2.3 released.

If it's ok, please close the issue 👍

**Comment by srtab** [comment]
Perfect, many thanks @Ks89!
