### ISSUE TITLE
[SURVEY] Which internationalization library are you using for your project with angular-modal-gallery?

### ISSUE THREAD

**Issue by Ks89** [Ks89/angular-modal-gallery#160]
I have a question for all users of this library.
Which internationalization library are you using for your project with angular-modal-gallery?
For instance: **angular-cli i18n**, **ngx-translate** or other stuff?

This survey is useful to plan future versions of the library (>=8.0.0).

Thank you.

**Comment by Ks89** [comment]
I'm asking this because I want to remove internationalization support via inputs, preferring a standard way like angular-cli i18n via "i18n-something" as already done by ng-bootstrap.
In this way, It will be easier to support many languages also for accessibility purposes.

**Comment by cuneytcalishkan** [comment]
ngx-translate is my choice, easy to use especially when combined with http-loader

**Comment by Ks89** [comment]
Ok, I decided to wait to change this. I want to see how runtime transtations will be implemented with angular ivy (render 3).
So, at the moment I close the issue.

When Angular's team decide a standard and well supported way to do this also at runtime, I'll implement it.
