### ISSUE TITLE
Length attribute of GridLayout not working

### ISSUE THREAD

**Issue by kaiwalyapowle** [Ks89/angular-modal-gallery#166]
Hi, i am using ks89/angular-modal-gallery v6.3.0

I want to implement PlainGalleryGrid layout where in i want to show only 1 item so i have kept the length in BreakConfig as 1.
Following is the code: 

` plainGalleryGrid: PlainGalleryConfig = {`
    `strategy: PlainGalleryStrategy.GRID,`
   ` layout: new GridLayout(`
    `  { width: "160px", height: "160px" },`
     ` { length: 1, wrap: true }`
 `   )`
`  };`

However it shows all the items there are in the array consisting of Image objects. 

When i use LineLayout, the length attribute works just fine. Following is the code: 

` plainGalleryRow: PlainGalleryConfig = {`
 `   strategy: PlainGalleryStrategy.ROW,`
 `   layout: new LineLayout(`
  `    { width: "160px", height: "160px" },`
  `    { length: 1, wrap: true },`
   `   "flex-start"`
  `  )`
`  };`

Here only one item is shown if length is 1 or two items are shown if length is 2 and so on

**Comment by Ks89** [comment]
Hi, sorry for the delay.

Why do you need a grid layout to show only an element instead of a grid? In this case LineLayout is better. Could you explain the use case?

**Comment by Ks89** [comment]
However the length property is used to limit the grid by the number of elements per row.

**Comment by kaiwalyapowle** [comment]
Hi, you are right. My use case is such that Line layout is preferred instead of Grid Layout. 

The use case is as follows:

I have multiple arrays of Images and i want to display the first image of each array as thumbnail in a masonry style grid and on clicking the thumbnail, each modal will display its respective images.

I earlier thought the Grid Layout will by default get me the intended result. But now i am using the LineLayout to display the first image as a thumbnail and I have applied my own css to display these thumbnails in masonry style
