### ISSUE TITLE
Modify spacing between thumbnails (more than 2 images)

### ISSUE THREAD

**Issue by MiaAlSaif** [Ks89/angular-modal-gallery#169]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## Current behavior

Currently the thumbnail images are poorly laid out, meaning there is no even spacing in between, especially vertically where the images basically connect.

## Expected behavior

I would like to add spacing between the thumbnails to be more esthetically appealing.  I have tried in different several ways to style the elements in my component css file, but was not successful.  I also was not able to locate any documentation on the subject.  Could you please advice on how to accomplish this?
 
## Minimal reproduction of the problem with instructions

My official live example on StackBlitz (based on https://stackblitz.com/edit/angular-modal-gallery-v5) is: 

## Environment (the most important section to fill very carefully)

<pre><code>
- Node version: v10.10.0 
- npm version: 6.4.1  
- Operating System and version: Mac  
- Angular version: 6.2.4 
- angular-cli version (or SystemJS/Webpack): 6.2.4 
- I'm using Server Side Rendering with angular-universal: YES
- I'm compiling with mode: PROD 

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
You are right I'll add a small margin in next releases.
However, right now you can create your own custom layout using your css. I have some examples both in the doc and in the repo.

**Comment by MiaAlSaif** [comment]
Hi,

Thank you for your prompt response.  I was unable to locate the docs on that, could you please directly link here?

Cheers!

**Comment by Ks89** [comment]
https://ks89.github.io/angular-modal-gallery-2018-v6.github.io/demo/plain-custom-desc

https://ks89.github.io/angular-modal-gallery-2018-v6.github.io/demo/plain-image-pointer

**Comment by Ks89** [comment]
Fixed in develop branch and scheduled for the next 7.0.0 beta version.

PS: 7.0.0 will be release in November, however right now you can use a custom layout using examples in my previous post.

Issue closed, thank your for the issue.

**Comment by MiaAlSaif** [comment]
Thank you for the links! I was able to adjust padding.
