### ISSUE TITLE
Image are small : how to change it from     width: 50px;     to width : 250px

### ISSUE THREAD

**Issue by Farooq-ThinkDigital** [Ks89/angular-modal-gallery#170]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions

My official live example on StackBlitz (based on https://stackblitz.com/edit/angular-modal-gallery-v5) is: 

## Environment (the most important section to fill very carefully)

<pre><code>
- Node version: X.X.X  
- npm version: X.X.X  
- Operating System and version:  
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
Please could you provide more information? Which version of the lib are you using?

Also, which images? Modal previews? If yes, which images?
Or are you talking about plain images. If needed post also a screenshot :)

**Comment by Farooq-ThinkDigital** [comment]
hi thank you for reply: am using "@ks89/angular-modal-gallery": "6.3.0",

**Comment by Ks89** [comment]
which images? Modal previews? If yes, which images?
Or are you talking about plain images. If needed post also a screenshot :)

**Comment by Farooq-ThinkDigital** [comment]
ks-modal-gallery:

 <ks-modal-gallery class="modal-gallery-css" [id]="4" [modalImages]="images"
                  style="height: 100px; width: 250px;"
                    ></ks-modal-gallery>

**Comment by Farooq-ThinkDigital** [comment]
first image array : before clicking.

**Comment by Ks89** [comment]
This style="height: 100px; width: 250px;" is totally wrong. You are using an angular component tag not a simple html tag. If you want to change the behavior of the component you have to use its apis.

Please check the official doc

**Comment by Ks89** [comment]
This is more advanced, but very useful: https://ks89.github.io/angular-modal-gallery-2018-v6.github.io/demo/plain-custom-desc

I close the issue, if you have other questions feel free to ask
