### ISSUE TITLE
"description" not found in 'ks-modal-gallery(v6.3.0)

### ISSUE THREAD

**Issue by shakerica** [Ks89/angular-modal-gallery#172]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Hey!
I'm trying to add a custom description as you have in your demo.

From what I can see when I try to add this piece of code in my HTML
<ks-modal-gallery [id]="42" [modalImages]="images"
                    **[description]**="customFullDescription"></ks-modal-gallery>
and in my TS: 
customFullDescription: Description = {
    strategy: DescriptionStrategy.ALWAYS_VISIBLE,
    // you should build this value programmaticaly with the result of (show)="..()" event
    customFullDescription: 'Custom description of the current visible image'
    // if customFullDescription !== undefined, all other fields will be ignored
    // imageText: '',
    // numberSeparator: '',
    // beforeTextDescription: '',
  };

I'm getting in console : "Can't bind to "description" since isn't a known property of ks-modal-gallery ".
I had a look in : modal-gallery.component and I can't find [description] property

Can you please advice what can I do further ?
Is it not supported ?

## Expected behavior

Customize description.

## Minimal reproduction of the problem with instructions

Add this template in html:
<ks-modal-gallery [id]="42" [modalImages]="images"
                    [description]="customFullDescription"></ks-modal-gallery>
Add this object in ts: 
customFullDescription: Description = {
    strategy: DescriptionStrategy.ALWAYS_VISIBLE,
    // you should build this value programmaticaly with the result of (show)="..()" event
    customFullDescription: 'Custom description of the current visible image'
    // if customFullDescription !== undefined, all other fields will be ignored
    // imageText: '',
    // numberSeparator: '',
    // beforeTextDescription: '',
  };

Open console - >  see error.

## Environment (the most important section to fill very carefully)

<pre><code>
- Node version: 8.12.0  
- npm version: 6.4.1 
- Operating System and version:  Windows
 Angular version: 7.0.2 
- angular-cli version (or SystemJS/Webpack): 7.0.4
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: DEBUG 

Browser:
- [X] Chrome (desktop) version 70
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version 11
- [ ] Edge version XX

**Comment by Ks89** [comment]
Hi, 
Right now I'm attending a conference and I don't have a pc, however which version of the library are you using?

**Comment by shakerica** [comment]
Hey ! 

Thanks for quick answer. 
The version of the library is 6.3.0 .
I think you can close this issue I  just discovered 3 minutes ago that in order to configure your description you need to add : [currentImageConfig] = {description: customDescription}. 
I think maybe demo needs to be updated or something:)

Thanks a lot!

**Comment by Ks89** [comment]
Ok perfect. Which demo? Stackblitz v6 or demos inside the repo?
