### ISSUE TITLE
Cannot read property 'pauseOnHover' of undefined

### ISSUE THREAD

**Issue by alvinmactal** [Ks89/angular-modal-gallery#177]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
The error appear when hovering in the image modal

## Expected behavior
There's no change in behavior i just recieved this error when opening a modal gallery

## Minimal reproduction of the problem with instructions
I also encounter

My official live example on StackBlitz (based on https://stackblitz.com/edit/angular-modal-gallery-v5) is: 

## Environment (the most important section to fill very carefully)

<pre><code>
- Node version:  v8.12.0
- npm version:  6.4.1
- Operating System and version:   Windows 
- Angular version: 6.1.10
- angular-cli version (or SystemJS/Webpack): 7.1.0
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
That property is supported only in version 7.2.0.

You should use always the last version of the library. Also the live example you linked is old. You must use version 7 as explained in official Readme.

I'll update github issue template to use version 7 and prevent future mistakes.

**Comment by Ks89** [comment]
Ok template updated with a link to https://stackblitz.com/edit/angular-modal-gallery-v7

If you still have issues, feel free to comment here.

**Comment by alvinmactal** [comment]
I just checked, I'm using the latest version of the library.

**Comment by alvinmactal** [comment]
I fixed it by adding the slide configuration.  [slideConfig]="{playConfig: {autoPlay: true, interval: 5000, pauseOnHover: true}

**Comment by Ks89** [comment]
You are right, this is a bug and it's happening in all examples except for E1 E2 E3 E4.
Thank u. I'll fixit today with a new release.

**Comment by alvinmactal** [comment]
You're welcome. Thank you!

**Comment by Ks89** [comment]
7.2.1 released
