### ISSUE TITLE
How can i select multiple thumbnail to delete or implement functionality from thumbnails

### ISSUE THREAD

**Issue by sunildipun** [Ks89/angular-modal-gallery#184]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions

My official live example on StackBlitz (based on https://stackblitz.com/edit/angular-modal-gallery-v7) is: 

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: X.X.X
- Node version: X.X.X  
- npm version: X.X.X  
- Operating System and version:  
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
You are free to use your custom implementation for thumbnails in plain gallery, but not in modal view.

Check the official example on stackblitz https://stackblitz.com/edit/angular-modal-gallery-v7

**Comment by Ks89** [comment]
...obviously, you have to implement the logic by yourself, but it's not so difficult.

**Comment by sunildipun** [comment]
Cool with that, implement my necessecity. Is there any way to play video and audio with this gallery module?

**Comment by Ks89** [comment]
I didn't implement it yes.
Probably I'll add this feature in the future

**Comment by Ks89** [comment]
Feel free to close the issue if it's ok
