### ISSUE TITLE
"Invisible" previous/next buttons on first/last item

### ISSUE THREAD

**Issue by jagoda-b** [Ks89/angular-modal-gallery#188]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

On first/last item in gallery the icons previous/next are invisible - I can click on place when I expect the button and it moves from first to last image or from last to first. 
![image](https://user-images.githubusercontent.com/50718224/63015577-9ae8e380-be91-11e9-97e6-54bde5fe6386.png)

## Expected behavior

The icons are visible.

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
you are right, it's a bug.
I'll fix it as soon as possible.

**Comment by Ks89** [comment]
Fixed, I'll publish 7.2.3 in some days. Please be patient. I'm doing some tests.

**Comment by Ks89** [comment]
I found another issue about side previews. Default slideConfig input is ignored by the library. It's happening in the last stable version and probably also some other previous releases.

I'll publish 7.2.3 tomorrow with those 2 fixes.

**Comment by Ks89** [comment]
Fixed in 7.2.3 and published on npm

**Comment by Ks89** [comment]
feel free to comment if you find the same problem also in 7.2.3

**Comment by jagoda-b** [comment]
Ok, thank you for fast fix :)

**Comment by jagoda-b** [comment]
Hello, 
I just checked the preview of new version and I see that on the first/last image the cursor still changes to "hand" when in place of the previous/next button. Please could you disable this behavior?

**Comment by Ks89** [comment]
Ok, I'll disabled it.

**Comment by Ks89** [comment]
7.2.4 released. The only that I can't change in this version is focus after a click. I'll try in future releases.
