### ISSUE TITLE
hide thumbnails

### ISSUE THREAD

**Issue by adventmedia** [Ks89/angular-modal-gallery#189]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>
How can I hide the thumbnails (with the modal gallery)? I just want to open the gallery from a button (or a link) — don't want to see the thumbnails on the page. Does this option currently exist? If not…

**Comment by Ks89** [comment]
I'm sorry for the delay.
I'll try to answer this evening or tomorrow. Please be patient 😊

**Comment by Ks89** [comment]
I'm sorry for the delay again.
Version 8.0.0 will improve this feature in a simpler way, but there is a way also today.

In [this example](https://ks89.github.io/angular-modal-gallery-2018-v7.github.io/demo/gallery-service) you can see a button to open the modal gallery using galleryService, but still with thumbs.
However, you can combine custom layouts of plain gallery with gallery service.

I modified the official live example for you to show you this here: https://stackblitz.com/edit/angular-modal-gallery-v7-vv9e59?file=src%2Fapp%2Fapp.module.ts

Feel free to try and experiment on that example.

If you have any questions feel free to ask.

**Comment by Ks89** [comment]
Is still an issue? If not can you close it?

**Comment by adventmedia** [comment]
sorry, not receiving notifications even though I'm subscribed… anyhow, yes, close this; I did eventually arrive at the solution you offer
