### ISSUE TITLE
Autoplay always enabled

### ISSUE THREAD

**Issue by aslubsky** [Ks89/angular-modal-gallery#191]
Look like autoplay ignore config value, on demo too
https://ks89.github.io/angular-modal-gallery-2018-v7.github.io/demo/carousel-noautoplay
it starts to play after 5s (checked in FF 69 and Chromium 76.0.3809.100)
I guess problem here https://github.com/Ks89/angular-modal-gallery/blob/master/projects/ks89/angular-modal-gallery/src/lib/components/carousel/carousel.component.ts#L377
it will show next image after initialization and them start play loop

**Comment by Ks89** [comment]
Hi I'm sorry for the delay. I'll check your pull request ASAP.

**Comment by Ks89** [comment]
You are right, it's a bug.

**Comment by Ks89** [comment]
released with your pr as 7.2.5
