### ISSUE TITLE
How on carousel image click to open modal gallery with current clicked image

### ISSUE THREAD

**Issue by varun2508** [Ks89/angular-modal-gallery#193]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## Minimal reproduction of the problem with instructions

My official live example on StackBlitz (based on https://stackblitz.com/edit/angular-modal-gallery-v7) is: 

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: X.X.X
- Node version: X.X.X  
- npm version: X.X.X  
- Operating System and version:  
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
Hi @varun2508 the official example already has this.

Go [here](https://stackblitz.com/edit/angular-modal-gallery-v7?file=src%2Fapp%2Fcarousel%2Fcarousel.component.html) and select "carousel" from the navigation bar (of the live example on the right), then check the example called `B2 - (id=111) - carousel example with fixed maxWidth (766px), custom previews and open modal on click`.

**Comment by Ks89** [comment]
Close because inactive.
Feel free to comment and/or reopen if it's still an issue.
