### ISSUE TITLE
Ability to set fallback image

### ISSUE THREAD

**Issue by sm-g** [Ks89/angular-modal-gallery#194]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When `ModalImage.img` or `PlainImage.img` points to url, returning 404, the default browser fallback image shown in place of PlainImage and still loading spinner in place of ModalImage.

## Expected behavior
Ability to set fallback image, i.e. to configure [`onerror` of `<img>`](https://stackoverflow.com/a/980948/3009578):

```
onerror="this.src='error.jpg';this.onerror='';"
```

## Environment
<pre><code>
- @ks89/angular-modal-gallery version: 7.2.1
- Operating System and version:  Windows
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: DEBUG

Browser:
- [ x] Any

**Comment by Ks89** [comment]
Interesting idea.

**Comment by Ks89** [comment]
Feature implemented and scheduled for angular-modal-gallery 8.0.0-beta.1 that is coming soon.
I pushed all commits into branch `800`.

I'm sorry for the big delay, but version 8, required a huge effort.

Issue closed.
