### ISSUE TITLE
All images in modal gallery re-fetched after every switch

### ISSUE THREAD

**Issue by timmyrosen** [Ks89/angular-modal-gallery#195]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

All images in the modal gallery are re-fetched from server every time I click to view another image in the gallery modal. This video is from the official docs site, but I have the exact same issue in my project:

![angular-modal-gallery2](https://user-images.githubusercontent.com/2311633/66472170-f8ae3c00-ea8c-11e9-8eca-9b84be1d184c.gif)

## Expected behavior
Already fetched images should not be re-fetched from the server.

## What is the motivation / use case for changing the behavior?
It's not an optimal behavior as of now. I have a rather large image array as well with 30+ images sometimes, that are all re-fetched when I click to view another image.

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: 7.2.5
- Node version: 12.6.0
- npm version: 6.9.0
- Operating System and version: MacOS
- Angular version: 8.2.5
- angular-cli version: 8.3.3
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: PROD with AOT

Browser:
- [x] Chrome (desktop) version 77.0.3865.90
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by Ks89** [comment]
Could check if all these requests are completed via server or cache?
In your video you disabled cache, so they obviously refetched.

**Comment by Ks89** [comment]
Is still an issue? If not could you close it?

**Comment by timmyrosen** [comment]
Wow.

Forgetting I had that checked. Unchecked and the issue is gone. I'm an idiot, closing :)
