### ISSUE TITLE
Dynamically constructing the image array without having to hardcode the images 

### ISSUE THREAD

**Issue by Sillergeoduck** [Ks89/angular-modal-gallery#196]
Hi, 
     Could you please point to me a example where i can construct the images array dynamically.  lets say i have a service that returns an Object like shown below :

```
{ 
   "Products":[ 
      { 
         "productId":1,
         "productCategory":"Test1",
         "ProductDescription":"Loreum Epseum",
         "ProductImage":"https://i.imgur.com/Hykr7by.jpg"
      },
      { 
         "productId":2,
         "productCategory":"Test2",
         "ProductDescription":"Loreum Epseum",
         "ProductImage":"https://i.imgur.com/Hykr7by.jpg"
      },
      { 
         "productId":3,
         "productCategory":"Test3",
         "ProductDescription":"Loreum Epseum",
         "ProductImage":"https://i.imgur.com/Hykr7by.jpg"
      },
      { 
         "productId":4,
         "productCategory":"Test3",
         "ProductDescription":"Loreum Epseum",
         "ProductImage":"https://i.imgur.com/Hykr7by.jpg"
      },
      { 
         "productId":5,
         "productCategory":"Test4",
         "ProductDescription":"Loreum Epseum",
         "ProductImage":"https://i.imgur.com/Hykr7by.jpg"
      }
   ]
}
```

now once i have that Products data in my component through service.. how can i construct the images array that you have showcased in your examples. from your example i see your images array looks like as shown below :
 ```
images: Image[] = [
    new Image(
     0,
      { // modal
        img: 'https://i.imgur.com/Hykr7by.jpg',
        extUrl: 'http://www.google.com'
      }
    )
  ];
```

so what i am specifically looking for is how to construct this piece in your array dynamically 
```
new Image(
     0,
      { // modal
        img: 'https://i.imgur.com/Hykr7by.jpg',
        extUrl: 'http://www.google.com'
      }
    )
```

your attention to it and help is much appreciated. since i am very new to angular my question might sound stupid also .. please bear with me on that. once again thanking you in advance. 

Please, before to submit this issue, try to remove both your `node_modules` folder and `package-lock.json` file.
Finally, run `npm install`.
If your problem is still present, fell free to open an issue with this template.
-->

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions

My official live example on StackBlitz (based on https://stackblitz.com/edit/angular-modal-gallery-v7) is: 

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: X.X.X
- Node version: X.X.X  
- npm version: X.X.X  
- Operating System and version:  
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
Hi, It's very easy. You have to subscribe to the observable returned by your service method. But actually this is not about this library but it's a general angular question. You should do something like this in your component:

```
constructor(private myservice MyService) {}

method() {
 this.myservice.servicemethod.subscribe(something => {
    // use this something to fill the images array
})
}

```
