### ISSUE TITLE
Not able to render the Modal view of the images passing multiple array of images

### ISSUE THREAD

**Issue by Sillergeoduck** [Ks89/angular-modal-gallery#197]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[x] Support request
</code></pre>

## Current behavior

**Not able to render the Modal view of the images passing multiple array of images . 

## Expected behavior

**Should create multiple Galleries by iterating through different set of array of images**
`  <div *ngFor="let image of ele.images; let i = index">
             <ks-modal-gallery [id]="i" [modalImages]="ele.images"></ks-modal-gallery>
    </div>`

## Minimal reproduction of the problem with instructions

please find the StackBlitz URL --> https://stackblitz.com/edit/angular-droqlv

In this if you see the in the app.component.html , i have written two different  Unordered lists
**First one without Ks-modal-gallery to show that there is data** 
**second with ks-modal-gallery to show that it is not rendering the modal view**

if you see app.component.ts , i have created data : Object from which i am trying to construct series of galleries based on the testid/testName. 

But when i tried to pass it through *ngFor loop , not sure where code fails. 

can you please help me fix this issue and help me see where i am doing it wrong. thank you. any Help is much `appreciated`

My official live example on StackBlitz (based on https://stackblitz.com/edit/angular-modal-gallery-v7) is: 

## What is the motivation / use case for changing the behavior?

I am trying to Create a project of images based on the Test type for a student. so when i select the each test type . it shows me all the images relevant to that test and when i click on the image it brings up the modal view.
## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: X.X.X
- Node version: X.X.X  
- npm version: X.X.X  
- Operating System and version:  
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
Hi, you must pass instances of Image class, not simple json objects

Use something like this:

**new Image(**
      4,
      { // modal
        img: 'https://raw.githubusercontent.com/Ks89/angular-modal-gallery/master/examples/systemjs/assets/images/gallery/pexels-photo-93750.jpeg'
      },
      { // plain
        img: 'https://raw.githubusercontent.com/Ks89/angular-modal-gallery/master/examples/systemjs/assets/images/gallery/thumbs/t-pexels-photo-93750.jpg'
      }
    **),**

**Comment by Ks89** [comment]
Also, You cannot pass additional info to the gallery as in your example.
Check the doc to see all possible values in the Image class

**Comment by Ks89** [comment]
Close because inactive.
Feel free to comment and/or reopen if it's still an issue.
