### ISSUE TITLE
Not being able to have a custom button that does not close the image.

### ISSUE THREAD

**Issue by giTonyx** [Ks89/angular-modal-gallery#201]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Not able to have a custom button that does not close the currently open image.

## Expected behavior
Have the ability, at least for custom buttons, to not close the image.

## Minimal reproduction of the problem with instructions
Don't think it's needed as it's not really a bug. But the official demo would work as a reference.

## What is the motivation / use case for changing the behavior?
I would like to have a custom button which will trigger a background action, but not close the modal image.
My use case is to create a subgallery so the user, while browsing the images, will select some of them with this button. The fact that it closes disrupts the process.

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: X.X.X
- Node version: X.X.X  
- npm version: X.X.X  
- Operating System and version:  
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

**Comment by Ks89** [comment]
Hi.
I'm not able to reproduce this issue.

Please could you create an example on https://stackblitz.com/ with a very minimal setup to show this problem?

**Comment by giTonyx** [comment]
I'll try to create one as minimal as possible tomorrow, if needed.
But in your live demo, in the modal gallery, example B24, I don't even see the buttons.

Can you see them?
And what happens if you click the custom button? Does it leave the image opened or does it close it?

**Comment by Ks89** [comment]
Yes there is a problem in live demo, probably because I'm importing font-awesome using an external service to show different buttons.



> And what happens if you click the custom button? Does it leave the image opened or does it close it?

Yes this is the expected behaviour.

**Comment by giTonyx** [comment]
I understand. Is there a way to alter, maybe via the hooks or via config so that it leaves the image open?

**Comment by Ks89** [comment]
No wait, probably I didn't explain well. The right behaviour is: when you click on a custom button, the gallery stays open. There are no reason to close the gallery. This is why I'm asking for a live demo to try to understand in which scenario this is happening.

In the source code I only emit events, nothing more. So the gallery should stay open.
Taken from modal-gallery.component.ts: 
```
  /**
   * Method called by custom upper buttons.
   * @param ButtonEvent event payload
   */
  onCustomEmit(event: ButtonEvent) {
    const eventToEmit: ButtonEvent = this.getButtonEventToEmit(event);
    this.buttonBeforeHook.emit(eventToEmit);
    this.buttonAfterHook.emit(eventToEmit);
  }
```

If you create a live demo in stackblitz I'll try to understand why you see that bad behaviour.

**Comment by giTonyx** [comment]
Hum.. that is quite weird. I've created a minimalist test and it works as you described indeed, on stackblitz.
But in my project I keep having this issue. Maybe some weird dependency? Maybe because I am using angular 9?
Anyway the problem is not in your library.

Sorry for wasting your time, should have created the minimalist example immediately.
