### ISSUE TITLE
Impossible to implement any grid

### ISSUE THREAD

**Issue by Nononolan45** [Ks89/angular-modal-gallery#204]
Hi, i am using ks89/angular-modal-gallery v7.2.5, and angular v8.0.

I am building the component gallery in my project with this package. All the functionality work,and to finish , i want to implement the "plainGalleryGrid". But at the time , the display does not appear, and any error. When i remove the plaingallerygrid , the display appear.

`    <ks-modal-gallery [plainGalleryConfig]="plainGalleryGrid" [modalImages]="images" [buttonsConfig]="customButtonsConfig" 
    (buttonBeforeHook)="onButtonBeforeHook($event)" ></ks-modal-gallery>`

`  plainGalleryGrid: PlainGalleryConfig = {
    strategy: PlainGalleryStrategy.GRID,
    layout: new GridLayout({ width: '80px', height: '80px', }, { length: 3, wrap: true }),
  };`

Sorry for my english , but i am french.

**Comment by Ks89** [comment]
> Sorry for my english , but i am french.

No problem :)

Please could you provide a live example based on the official stackblitz demo https://stackblitz.com/edit/angular-modal-gallery-v7 ?

Because It's easier for me to help you and you could try to re-create your problem in a different project.

**Comment by Nononolan45** [comment]
The conflict come to other library (modal-gallery-modal)  declared in app.module.
Thanks for help.
