### ISSUE TITLE
Can't resize a thumbnail / plain image 

### ISSUE THREAD

**Issue by studiocuboweb** [Ks89/angular-modal-gallery#206]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

In the Image array:
new Image(0, {
      img: '../assets/large.jpg?dsadsa=dasdsa',
      extUrl: 'http://www.google.com',
    },{img: '../assets/guru-badge.png?dsadsa=dasdsa',
      description: 'teste',
      alt: 'teste',
      ariaLabel: 'arial label 2',
      size: {width: '100px', height: 'auto'} 
}),

The size param is not changing and the default value width:50px height:auto still remains in the plain thumb.

## Expected behavior

that the default value changes to the width and height that are in the size params.

## Minimal reproduction of the problem with instructions

1. Changed the size of plain thumb, and the image, refresh the browser and the image is changed, but the size not... still the default width;50px height:auto

## What is the motivation / use case for changing the behavior?

For layout and design purposes. I need to change the thumbnail plain size.

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: 7.2.5 
- Node version: 12.16.1
- npm version:6.13.4  
- Operating System and version:  MAC OS 10.14.6
- Angular version: 
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@angular/cdk                      9.2.4
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

- angular-cli version (or SystemJS/Webpack): 8.1.3 
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: DEBUG 

Browser:
- [x] Chrome (desktop) version 83.0.4103.97 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
Hi @studiocuboweb. Are you able to recreate this issue with the official live demo https://stackblitz.com/edit/angular-modal-gallery-v7/ ?

**Comment by Ks89** [comment]
I'm investigating because I don't have any example of this, however to change the plain gallery size I suggest to use PlainGalleryConfig. For instance:

```
plainGalleryRow: PlainGalleryConfig = {
    strategy: PlainGalleryStrategy.ROW,
    layout: new LineLayout({ width: '80px', height: '80px' }, { length: 2, wrap: true }, 'flex-start')
  };
```

**Comment by Ks89** [comment]
I'll remove the size option in that interface.

I confirm to use PlainGalleryConfig with the layout you want specifying the size.

**Comment by Ks89** [comment]
I removed size option in PlainGalleryConfig in 8.x.x. So I close this issue. Feel free to re-open it if you think that it's still an issue
