### ISSUE TITLE
Event for handling for moving to the next picture in <ks-modal-gallery>

### ISSUE THREAD

**Issue by pLazy** [Ks89/angular-modal-gallery#207]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I need to change the icon on a button on one of the pictures in a modal gallery, and it seems like I cannot do it out of the box. 

## Expected behavior

It would be great if we can have an event " onPictureFocus" which returns the picture id as soon as the picture is the one visualized in the modal.

**Comment by Ks89** [comment]
Hi @pLazy,
I don't understand your problem, please could you add more details?

The current version emits show event when you navigate across images. Every time the current image changes, a new ImageModalEvent will be emitted using the show output.

With 'onPictureFocus', do you need to know when a user focuses the current image in modal-gallery or simply the id of the current image? If your question is the first one, at the moment it's not possibile, instead, if you need the id of the current image, you can use the show event as explained above.

**Comment by pLazy** [comment]
Hi Ks89!

You are right! I am sorry I couldn't find it in the documentation. It works like a charm, thank you ;). 
I tried to figure out from this [page](https://ks89.github.io/angular-modal-gallery-2018-v7.github.io/features) but I couldn't find it. 

If I may ask you (for not opening a new issue as it might be an ignorance of the documentation from my side) when I try to delete a picture, it seems as if the input doesn't update/refresh until the list of images are empty. I tried with the following code, and the images are always present on the page until I close the image list is empty.

**Typescript**:


```
  newImage: Image[] = [
    new Image(
      0,
      { // modal
        img: 'https://www.thomsn.at/wcms/Clients/501485728561537/Images/687827201938081219.JPG',
        extUrl: 'http://www.google.com'
      }),
    new Image(
      1,
      { // modal
        img: 'https://www.wien.info/media/images/tian-restaurant-vegetarisch-19to1.jpeg',
        extUrl: 'http://www.google.com'
      })
  ];

   deleteElement($event: ButtonEvent) {
    // this.newImages.splice(0, 1);
    this.newImage.pop();
  }
```

**Html**:

```
<ks-modal-gallery *ngIf="newImage.length > 0" [id]="0" [modalImages]="newImage" [plainGalleryConfig]="plainGalleryRowATags"
                  [modalImages]="newImage"
                  [buttonsConfig]="buttonsConfigCustom"
                  (buttonAfterHook)="deleteElement($event)" (show)="test($event)"
                  ></ks-modal-gallery>
```

 Thank you very much for your answer :)

**Comment by Ks89** [comment]
You cannot change the input image array. Instead, you should reassign it with a newer array without the deleted element. In other words, you must think in a functional way, without changing the input array of images. For more information check this official demo https://stackblitz.com/edit/angular-modal-gallery-v7/?file=src%2Fapp%2Fmodal-gallery%2Fmodal-gallery.component.html, example B21 - (id=30)
