### ISSUE TITLE
Trouble while loading images from api

### ISSUE THREAD

**Issue by adam-mikeska** [Ks89/angular-modal-gallery#209]
Hello i have trouble while loading images..

This is how i do it

```
  imagesRect: Image[] = [
    new Image(
      0,
      {
        img: '',
      },
      {
        img: '',
      }
    ),
  ];

    this.apiService.findProduct().subscribe(
      res => {
        const images: Image[] = [];
        for(let i=0;i<res?.productImages.length;i++){
          images.push(
            new Image(
              i,
              {
                img: 'http://localhost:8080/product/image/'+res.product.title+'/'+res.productImages[i].image,
              },
              {
                img: 'http://localhost:8080/product/image/'+res.product.title+'/'+res.productImages[i].image,
              }
            ),
          )
        }
        this.imagesRect=images;
      }
```

so when images are not loaded and i click on arrow images got loaded. 
also when i click on empty image like on screenshot bellow, images are present in modal gallery
But loading on main page is way too slow..

![image](https://user-images.githubusercontent.com/56235326/90951761-e5664e00-e45d-11ea-91da-0dc5b2dd8d53.png)

video : https://www.youtube.com/watch?v=Bb7tUbGpfeU

**Comment by hvsharma63** [comment]
> When i do this with ks-modal-gallery it works as it should... I dont know why i got those troubles with ks-carousel

How did you solve the issue?
I'm facing the same issue

**Comment by Ks89** [comment]
@hvsharma63 

I suggest to hide the carousel when the array is empty with an *ngIf="show" or *ngIf="arrayofImages.length === 0".
When the rest api returns data, in the subscribe(...) you can init the show variable or add the elements into arrayofImages.
In this way, the carousel will be visible with your images.
You could also display a custom spinner when show = false or arrayofImages.length === 0 to improve UX.
