### ISSUE TITLE
DIsplay previews on small screens

### ISSUE THREAD

**Issue by vlafranca** [Ks89/angular-modal-gallery#213]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## Current behavior
Hi,
I noticed that the previews are hidden by default on small screens (>768px) via css rules inspectables in the browser. Is it possible to keep previews on screens below 768px ?
Best solution would be to be able to customize this : 
```
@media only screen and (max-width: 767px), only screen and (max-device-width: 767px) {
.previews-container {
 display: none;  
 > .preview-image {
 display: none;
 }

```

Thanks in advance

## Expected behavior
Previews should be displayed on small screens

## Minimal reproduction of the problem with instructions
Open any modal example on the live demo, then shrink your browser width, the previews will disapear.

## What is the motivation / use case for changing the behavior?
Would be nice to have to customize whether or not we want to display the previews on small screens

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: latest
- Node version: 12  
- npm version: 12  
- Operating System and version:  Windows
- Angular version: 9
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: DEBUG

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by Ks89** [comment]
Hi, I'm sorry for the delay.
At the moment this is not possible.

**Comment by vlafranca** [comment]
May I know why ?
Can i submit a PR ?

**Comment by Ks89** [comment]
Because, I didn't implement it.

If you want yes, however, please use branch develop to add this feature to the next major release 8.0.0.

**Comment by vlafranca** [comment]
Great I will submit something soon

**Comment by Ks89** [comment]
pull request merged
