### ISSUE TITLE
Angular 11 moduleWithProvider<T> type is required.

### ISSUE THREAD

**Issue by cihancelen** [Ks89/angular-modal-gallery#215]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I upgraded the version of the Angular project to 11. After the upgrade, in the modal-gallery.module-> forRoot () method, I saw that ModuleWithProviders class requested type and crashed while getting build.

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: X.X.X
- Node version: v10.13.0  
- npm version: 6.4.1  
- Operating System and version: Mac  
- Angular version: 11.0.2 
- angular-cli version (or SystemJS/Webpack): 11.0.2 
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [X] Chrome (desktop) version 86.0.4240.198 (Official Build) (x86_64)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

![image](https://user-images.githubusercontent.com/23706015/100900924-678df600-34d4-11eb-8ba3-2fa82befe4b0.png)

**Comment by Ks89** [comment]
Thank you for the PR #216 I'll merge it weekend.

**Comment by cihancelen** [comment]
Hi, I would be glad if you can publish to npm as soon as possible. Because now I forked the project and built it locally and I use it in my own project :)

Good work ✋

**Comment by Ks89** [comment]
Sure, I'll publish the new release tomorrow 👍

**Comment by Ks89** [comment]
release 7.2.7
