### ISSUE TITLE
backdrop does not cover entire window

### ISSUE THREAD

**Issue by adventmedia** [Ks89/angular-modal-gallery#220]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Backdrop for modal gallery does not completely cover the window as expected

## Minimal reproduction of the problem with instructions
go to https://almacrae.com/news and click link "See some pics".

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: 7.2.7
- Node version: 12.18.1
- npm version: 6.14.11
- Operating System and version:  MacOS 10.14.6
- Angular version: 11.2.6
- angular-cli version: X.Y.Z: 11.2.5
- I'm using Server Side Rendering with angular-universal:NO
- I'm compiling with mode: PROD with AOT

Browser:
- [x] Chrome (desktop) version 89
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 14.0.x
- [x] Safari (iOS) version iOS 14.4.1 - WORKS
- [ ] IE version XX
- [ ] Edge version XX

Others:
the backdrop is positioned with 'fixed' which should work (there are reported cases where a fixed div is used within a div that uses a transform, but does not appear to be the case here. (Other components that use backdrops (click on the images on the right of the referred page) place them outside the dom with absolute positioning)

**Comment by Ks89** [comment]
I suggest to try the beta version of 8.0.0. It's already working. I miss a unit test and to update the documentation before the final release. When I'll have some spare time I'll try to release the final version.

In v8.0.0 I used angular overlay as in material to fix the position. For sure, it's better than the current implementation.

**Comment by adventmedia** [comment]
I tried the beta but as the api is so different, w/o docs it was simpler just to use a different component (lightbox)

**Comment by Ks89** [comment]
Yes I understand. I created many live examples in `examples` folder to show how it works and to cover many scenarios. Except for modal-gallery open method via service, all the rest is exactly the same. I tried to do minimal changes.
Here there is also the stackblitz live example: https://stackblitz.com/edit/angular-modal-gallery-v8/

Please close the issue, if you think that it's ok.
