### ISSUE TITLE
How to change the margin of the images  mesonary grid

### ISSUE THREAD

**Issue by danurasenan** [Ks89/angular-modal-gallery#221]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Minimal reproduction of the problem with instructions

My official live example on StackBlitz (based on https://stackblitz.com/edit/angular-modal-gallery-v7) is: 

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: X.X.X
- Node version: X.X.X  
- npm version: X.X.X  
- Operating System and version:  
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment]
Please could you explain your problem in details, also with a live example or a screenshot?
Are you talking about plain-gallery or modal-gallery?

**Comment by danurasenan** [comment]
@Ks89 
 hi.  thank you for your response, im talking about modal gallery. you can see the red arrow between two images. i want to reduce that margin.
![Capture](https://user-images.githubusercontent.com/78210064/113015010-be61be80-919a-11eb-92de-1eb23ed6361a.PNG)

**Comment by Ks89** [comment]
Oh I totally missed your response.
You have to use your own custom css with a custom plain gallery

**Comment by danurasenan** [comment]
Thank you for your response
