### ISSUE TITLE
How can i change the background color of image viewer

### ISSUE THREAD

**Issue by danurasenan** [Ks89/angular-modal-gallery#225]
**I want to change the background color after image is open.currently its look black with opacity. i want to change it to white.

i try to change it using custom css for div id "modal-gallery-wrapper". but its not working. 

can anyone help me to change this**

![Capture](https://user-images.githubusercontent.com/78210064/120679775-2c867280-c4b7-11eb-879c-b0a9682f3812.JPG)

**Comment by Ks89** [comment]
Hi.
Version 7.x.x doesn't support this feature.
However the next release 8.0.0-beta adds this possibility via CSS.

If you want to use the beta version (already stable, don't be scared) you can change background color.
Doc website for v.8.0.0 in under development (mostly done) and not published live, however a full set of examples is available here https://github.com/Ks89/angular-modal-gallery/tree/develop/src

**Comment by Ks89** [comment]
I close the issue, because already done in v.8.0.0. For more info about v.8.0.0 features check #183

**Comment by locinus** [comment]
Hi there! So I'm interested in that too, but I can't find how to do it in the doc... any hint?

**Comment by Ks89** [comment]
@locinus you are right, I forgot to add it to the doc. Scheduled for v10.0.0.

To change background check this file https://github.com/Ks89/angular-modal-gallery/blob/develop/src/styles.scss
as you can see you can define your own color:

```
.ks-modal-gallery-backdrop {
  background: #000 !important;;
  opacity: 0.85 !important;;
}

.ks-modal-gallery-panel {
  z-index: 90000 !important;
}
```

**Comment by locinus** [comment]
Hi! Oh yes, I see.
Because I believe some users who don't want a dark background will wish for a white one (more than any other color), with assorted buttons, I post here a css suggestion to do so:

```
.ks-modal-gallery-backdrop {
  filter: invert(1);
}
ks-upper-buttons .upper-button,
ks-current-image .left-arrow-image,
ks-current-image .right-arrow-image {
  filter: invert(0.7);
}
```

I might have forgotten some widgets I'm not using though!
