### ISSUE TITLE
Allowing custom templates for previews or modal image

### ISSUE THREAD

**Issue by locinus** [Ks89/angular-modal-gallery#243]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
It doesn't seem to be possible to customize the rendering of the preview images, by example to add some labels to the previews. Especially, I don't think the gallery allows to provide templates for its subcomponents?

## Expected behavior
The library could provide a means to customize the rendering of preview images, or the model image, via Angular templates to allow maximum flexibility.

## What is the motivation / use case for changing the behavior?
Maximize usability!

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: 7.2.5
- Node version: 14.15.0
- npm version: 6.14.8
- Operating System and version:  Windows 10
- Angular version: 11.2.0
- angular-cli version: 11.2.4
</code></pre>

**Comment by Ks89** [comment]
Thank for you feedback.
This is something that I can add in future releases because it seems interesting. The same was already asked for carousel previews, so It seems reasonable to do the same also in modal gallery.

**Comment by locinus** [comment]
Hi there!
Nothing sure, but I might take a look at that in the next weeks. Any development on your side regarding this that I should be aware of?
(I'm still using version 8 on my Angular 12 app though, so I'll so how it goes.)

**Comment by Ks89** [comment]
Hi, no this is scheduled for version 10.0.0.
Any contribution is well accepted. Thanks to version 9, I removed IE11 support, so it will be easier to implement it without losing time to add workaround and other boring things to support Internet Explorer 11.

Feel free to share your thoughts about how to implement this features, because it sill require a discussion before to write code. I'm open to feedbacks and suggestions.

**Comment by locinus** [comment]
Hi! So I've been playing with the code a little, just to know what could be possible to do. First, I'd like to talk about the initial need related to this suggestion, and then about some ideas of implementation.

### The complete initial need

I need to show some information about the pictures shown in the preview area.
At the moment, if we make them customizable, this could be achieved, using the 'description' attribute of ModalImage:
![ks customized preview - proto](https://user-images.githubusercontent.com/29314302/151617257-3f8c4b58-5e2d-434d-a1a0-b30f70881c59.jpg)
It's nice, but ultimately, I'd like to use picture-specific information which (if I'm not wrong) can not fit anywhere in the ModalImage object, such as the picture date for instance. So to fully be able to do so, an evolution to add a custom Object in ModalImage, whose data could be used in template customizations, would be necessary, so that's to be discussed.
 
### Implementation options

The idea to customize the previews would be to leverage the Content Projection mechanisms. As the gallery (at least modal) does not use HTML node anymore and is programmatically open, I would tend to go to mechanisms inspired by this blog post: https://blog.angular-university.io/angular-ng-template-ng-container-ngtemplateoutlet/

The idea would be, to summarize:
- to define a custom template (with ng-template) for the previews, **in the consumer Component**
- to pass a reference to that template **within the ModalGalleryConfig**, when calling ModalGalleryService:open()
- **in ModalGalleryComponent's template**, to pass this (optional) template reference as an input of ks-previews
- **in PreviewsComponent's template**, to use that custom template if any was provided, or to use a default template (which renders what is currently rendered)
- the custom template created at first in the consumer Component is given access (_via template context_) to some objects:
  - **the 'preview' object** (from the PreviewsComponent's template for-of)
  - and maybe **the preview's default template** so it's possible to "wrap" it while still using its functionnalities

I have a working prototype rendering the above image. If you wish, I can make it a PR to serve as a base for the discussion. I'm also very much interested in hearing alternative solutions, if any comes in mind!

**Comment by Ks89** [comment]
Thank you. 
I'm very busy these days, so I'm sorry if I'm really slow to read and check issues.
I'll check it before the end of the week.

**Comment by Ks89** [comment]
Ok, yes I interested to see your implement.
Feel free to create a pull request. It will be easier to discuss reading some code.

**Comment by locinus** [comment]
Hey. Sorry, quite busy myself as well.
I just created a PR with core and example modifications in it, so you can check it out.

It's my first PR, so please comment or advise if I got anything wrong in the process! : )
