### ISSUE TITLE
modalGalleryEnable not working for <ks-carousel>

### ISSUE THREAD

**Issue by Sandervanmaurik** [Ks89/angular-modal-gallery#247]
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

I am using a ks-carousel tag to show images in my Angular application.
I added the [config] to inject the config property in my .ts file. I noticed that the config is working for most properties, but not for modalGalleryEnable: true. 

## Expected behavior
[config] tag should apply the config.
I expect the modalGalleryEnable: true property to open de image in a modal.

## Minimal reproduction of the problem with instructions

I added the following code to my .HTML file:

            <ks-carousel [id]="100" [images]="photos" [config]="carouselLibConfig"></ks-carousel>

I added the following code to my .ts file:
<pre> <code>
carouselLibConfig: CarouselLibConfig = {
    carouselConfig: {
      maxWidth: '100%',
      maxHeight: '400px',
      showArrows: false,
      objectFit: 'cover',
      keyboardEnable: true,
      modalGalleryEnable: true
    },
    carouselDotsConfig:{
      visible: false
    },
    dotsConfig: {
      visible: false
    },
    previewConfig:{
      visible: true,
      arrows: false,
      clickable: true,
      mobileVisible: true,
    }
  }

photos: Image[] = [];
</code></pre>
 
Also I added images to the array like this:
        <code>this.photos.push(new Image(Math.random(), { img: "/assets/images/edupd/patienten-overzicht-docenten.PNG" }));

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: 9.0.3
- Node version: 16.3.0 
- npm version: 8.2.0 
- Operating System and version:  Windows 11
- Angular version: 13.0.3 
- angular-cli version (or SystemJS/Webpack): @angular/cli 13.0.4 
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: DEBUG

Browser:
- [x] Chrome (desktop) version 96.0.4664.45

Others:
</code></pre>

![image](https://user-images.githubusercontent.com/16664678/145051407-f5af3920-de27-468f-9f91-960b649c8c06.png)

**Comment by Ks89** [comment]
Hi, you have to use the (clickImage) output in this way:

```
<ks-carousel [id]="114" [images]="imagesRect" [config]="LIBCONFIG114" (clickImage)="openModal($event, 114)">
    <div class="projected">This is my projected content!</div>
  </ks-carousel>
```

and then 

```
openModal(imageIndex: number, id: number): void {
    const imageToShow: Image = this.imagesRect[imageIndex];
    const dialogRef: ModalGalleryRef = this.modalGalleryService.open({
      id,
      images: this.imagesRect,
      currentImage: imageToShow
    } as ModalGalleryConfig) as ModalGalleryRef;
  }
```

Check this example: https://github.com/Ks89/angular-modal-gallery/tree/develop/examples/angular-cli-13/src/app/carousel


I should add this example in the doc website as a live example :).

**Comment by Ks89** [comment]
Hi @Sandervanmaurik is this still an issue?

**Comment by Sandervanmaurik** [comment]
Hey thankyou for the reply! I missed your answer and see it now. I will try this on monday and will let you know if it works now.
