### ISSUE TITLE
GalleryService and navigateGallery have disappeared in 900

### ISSUE THREAD

**Issue by locinus** [Ks89/angular-modal-gallery#248]
## I'm submitting a...

<pre><code>
[X] Documentation issue or request
</code></pre>

## Current behavior

I used to work with GalleryService, which was offering methods: openGallery and navigateGallery.
When bumping to version 900, this service and these methodes are not to be found.

## Expected behavior

I couldn't find how to do the migration in the changelogs or migration instructions.
Could you help?

**Comment by Ks89** [comment]
From which version are you trying to upgrade (8 to 9 or 7 to 9)?

**Comment by Ks89** [comment]
If you are using 7.x.x I suggest to upgrade to 8.0.0 first (https://ks89.github.io/angular-modal-gallery-2020-v8.github.io/migration), and then to 9.0.0 (https://ks89.github.io/angular-modal-gallery-2021-v9.github.io/migration).

**Comment by locinus** [comment]
Thank you!
I was missing the 7->8 migration guide.

About that, I'm not entirely sure how I would have found the v8 documentation page (and its migration section) without you telling me.
I'm under the impression that the GitHub README (https://github.com/Ks89/angular-modal-gallery) only links to the **last** version documentation page, and that documentation pages **do not** offer navigation links to one another.
If this is the case, surely this would be a nice improvement to the documentation.

**Comment by Ks89** [comment]
You are right about the missing path from 7 to 8.

The broken navigation is related to something about github pages. I should move doc website on a dedicated server.
