### ISSUE TITLE
ks-plain-gallery  - Remove title from image when modal is open and delete image

### ISSUE THREAD

**Issue by CristianVallecchia** [Ks89/angular-modal-gallery#249]
Hi. How to remove or replace the text "image 1/x" from images when modal is open?
If possible delete immage with  plain gallery with figcaption?

**Comment by Ks89** [comment]
Please fill the issue template with all versions that you are using. I cannot provide support without all required info. Thanks

**Comment by CristianVallecchia** [comment]
if possible add Figcaption on plain gallery with column design?

<pre><code>
- @ks89/angular-modal-gallery version: 9.0.1
- Node version: v16.13.2
- npm version:8.3.1
- Operating System and version:  windows 10
- Angular version: 13.1.0
- angular-cli version (or SystemJS/Webpack):  13.1.3
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: PROD



Browser:
- [ ] Chrome (desktop) version 97.0.4692.71 

</code></pre>

**Comment by Ks89** [comment]
> Hi. How to remove or replace the text "image 1/x" from images when modal is open?

Check the doc website. There is an example https://ks89.github.io/angular-modal-gallery-2021-v9.github.io/demo/description-strategy to define custom descriptions. You can also use different strategies (check here https://ks89.github.io/angular-modal-gallery-2021-v9.github.io/features/description) to hide descriptions.
These are the available options:
```
ALWAYS_HIDDEN: description is always hidden
ALWAYS_VISIBLE: description is always visible
HIDE_IF_EMPTY: description is visible if valid
```

> If possible delete immage with plain gallery with figcaption?
I don't understand your question.
