### ISSUE TITLE
Scrollbar always visible on the right (.cdk-global-scrollblock set on <html>)

### ISSUE THREAD

**Issue by locinus** [Ks89/angular-modal-gallery#250]
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## Current behavior

Since version 8+, in the modal layout, a blank scroll bar is always visible on the right of the gallery.

This is certainly due to the automatic adding of the 'cdk-global-scrollblock' class on the <html> node, maybe due to the use of BlockScrollStrategy in ModalGalleryService:getOverlayConfig.
Was there a motivation to use this instead of the NoopScrollStrategy for instance?

## Expected behavior

No scrollbar on the right! : )

## Minimal reproduction of the problem with instructions
On https://ks89.github.io/angular-modal-gallery-2021-v9.github.io/demo/array-simple, "Examples" section, click on the 1st Live demo link.

## What is the motivation / use case for changing the behavior?

The scrollbar is unused and most likely unwanted.

## Environment (the most important section to fill very carefully)
The one of the demo website https://ks89.github.io/angular-modal-gallery-2021-v9.github.io/demo/array-simple, "Examples" section.

Browser:
- [X] Chrome (desktop) version 97
- [X] Firefox version 96

</code></pre>

**Comment by Ks89** [comment]
Give some days to try to investigate a bit because I cannot reproduce the issue quickly. 👍

**Comment by locinus** [comment]
Oh there is no rush! Just reporting. 
Can you not see it through the live examples of the doc page? It would depend on the browser or OS (I'm on Windows) then?

**Comment by Ks89** [comment]
You are right. It happens on Windows.
I don't remember why I used BlockScrollStrategy. Did you try to re-build the library using NoopScrollStrategy?

**Comment by locinus** [comment]
No, I haven't.

**Comment by Ks89** [comment]
Ok, I'll try it this weekend

**Comment by Ks89** [comment]
I tried but using the NoopScrollStrategy it permits page scrolling.

Doc says: "... Note that some applications may implement special or customized page scrolling; if the BlockScrollStrategy conflicts with this kind of situation, it can be overridden by re-providing BlockScrollStrategy with a custom implementation.".

Probably the only way to fix this is applying some customization. 
Did you see this issue only on Windows or does it happen also on smart phones, like iOS devices?
I feel worried to change this, because I cannot test all devices.

**Comment by locinus** [comment]
Indeed you're right. Noop might not be the greatest option.

From my tests:
- Windows: displeasing scrollbar
- Linux (Ubuntu): thinner scrollbar, more acceptable
- Android: invisible scrollbar, all good

I don't know about iOS smartphones, but I'd say it must be like iOS computers with invisible scrollbars?

So I think a workaround for people wanting to get rid of it on all devices would be to add in the application `styles.css` :
```
.cdk-global-scrollblock {
    overflow: hidden !important;
}
```

One should be careful if they're using Cdk elsewhere in their application though.
