### ISSUE TITLE
Small clipping on previews

### ISSUE THREAD

**Issue by locinus** [Ks89/angular-modal-gallery#253]
## I'm submitting a...

<pre><code>[X] Bug report  
</code></pre>

## Current behavior

There's a small clipping appearing within the preview pictures when clicking on the second preview, or, if we reached the last picture, when clicking on the preview before-the-last.

Fast snapshots of this behavior show this when we click on the second preview:
![image](https://user-images.githubusercontent.com/29314302/159592383-f7c10b70-4c1d-4f17-9b8a-dac57496b372.png)
![image](https://user-images.githubusercontent.com/29314302/159592331-caa81fcd-cf70-42bc-aa10-91a03fe78895.png)
![image](https://user-images.githubusercontent.com/29314302/159592345-2d2ce5a8-ebd6-42c1-bc7d-d756089d14fb.png)
_(sorry, the snapshots have been taken on the PR with the description on top of the previews; behavior is the same on the branch with no description on top of the previews)_

The click triggers the load of following resources:
![image](https://user-images.githubusercontent.com/29314302/159593851-817bc588-63ff-4121-bd47-17ece6fd4f65.png)

I haven't dived yet into the code, but if time allows, I'll check it out.
In the meantime, any hint about why the first preview would disappear for a very short time?

**Comment by Ks89** [comment]
No idea. It's weird because it should be cached by the browser when loaded the first time.
When you open the gallery without clicking anything, all visible images should be downloaded and cached by the browser.
I'll investigate a bit to understand if the browser is downloading the same image multiple times without caching or is something different.

I'm open to other approaches to debug this.

**Comment by locinus** [comment]
I got it ! = )
I'll do a PR, but tell me: each commit I push goes on my previous PR... do you know how to proceed to do otherwise and assign such commit to such PR?

**Comment by Ks89** [comment]
If your fix doesn't change anything about look and feel of previews, so it could be considered as backward compatible, I think you could add it to the same PR. Otherwise, for breaking changes we need a different PR and the fix will be part of versione 10.0.0.

How did you fix this?

**Comment by locinus** [comment]
I had a solution, but the system is much more complex so I'll have to work on it further.
I write here my current analysis for your information, but I'll dig through it.

**The problem**
The previews are **systematically** shifted back or forth, in previous() and next(). The thing is that, when coming from the 1st preview to the second by clicking on it, the previews /shouldn't change/, due to their disposition. Same when coming from the last to the before-the-last.
So they are shifted for a few frames, but then, due to an update of the 'images' input, the previews are recalculated correctly, hence the good 'final' result we obtain, yet resulting in a short flickering.

**A non-solution**
I had this fix in mind (here: for next()):

    ...
    if (this.end === this.images.length) {
      return;
    }

    const currentIndex = this.currentImage ? getIndex(this.currentImage, this.images) : undefined;
    if(currentIndex === 1) {
      // We're coming from index 0, the first image:
      // the previews don't change then, only the active preview changes.
      return;  
    }

    this.start++;
    ...

This fix works when clicking on the previews themselves, but clicking on the preview arrows makes it another problem. The fact that both clicking the preview (and updating currentImage) and clicking the preview arrow (not updating currentImage) go through next() with no distinction could be a problem.

**Many more questions**
Additionnally, there are many little things that I can't get straight and should be investigated:
- why do the 'images' input change occur? it's currently making things right for this issue, but we are entering block 178-181 of previews.component.ts where we shouldn't, as the situation does not fit the cases described in the comments and 'images' values (previous, next) are the same.
- how come my suggested fix works when we only render one preview?
- often, the number of previews will oscillate depending on the active image, between n-1 and n+1 (only n=1 and n=3 seem stable)
- how come in previews, end - start = (previewsNumber + 1)?
- there's an existing little quirk: when opening the modal and navigating to the last preview by **clicking** on the right preview arrow, it's impossible to then click on the left preview arrow: isPreventSliding() prevents it.
