### ISSUE TITLE
Carousel: No provider for Overlay

### ISSUE THREAD

**Issue by syrok0010** [Ks89/angular-modal-gallery#256]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
I have the following module structure
AppModule
->NavigationModule
->AdminPanelModule->HotelModule
My component with carousel is located in HotelModule
```
<div class="container" *ngIf="photos$ | async as photos; else loading">
    <ks-carousel [id]="600" [images]="photos" [config]="config"></ks-carousel>
    <app-hotel-gallery-form></app-hotel-gallery-form>
</div>
<ng-template #loading>
    <tui-loader
        [showLoader]="true"
        [size]="'xl'"
        [textContent]="'Подождите, идет загрузка...'"
    >
    </tui-loader>
</ng-template>
```
It produces the following error
```
ERROR Error: NullInjectorError: No provider for Overlay!
    at NullInjector.get (core.mjs:11140:1) [angular]
    at R3Injector.get (core.mjs:11307:1) [angular]
    at R3Injector.get (core.mjs:11307:1) [angular]
    at R3Injector.get (core.mjs:11307:1) [angular]
    at injectInjectorOnly (core.mjs:4765:1) [angular]
    at Module.ɵɵinject (core.mjs:4769:1) [angular]
    at Object.ModalGalleryService_Factory [as factory] (ks89-angular-modal-gallery.mjs:3816:1) [angular]
    at R3Injector.hydrate (core.mjs:11477:1) [angular]
    at R3Injector.get (core.mjs:11296:1) [angular]
    at NgModuleRef.get (core.mjs:21867:1) [angular]
    at R3Injector.get (core.mjs:11307:1) [angular]
    at NgModuleRef.get (core.mjs:21867:1) [angular]
    at R3Injector.get (core.mjs:11307:1) [angular]
    at NgModuleRef.get (core.mjs:21867:1) [angular]
```
I found a fix: add MatMenuModule to NavigationModule (don't ask why)

## Expected behavior
No need to use MatMenuModule

## Minimal reproduction of the problem with instructions
TODO

## What is the motivation / use case for changing the behavior?
Less dependencies, smaller bundle size

## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: 9.0.1
- Node version: 17.9.0
- npm version: none
- yarn version: 1.22.18
- Operating System and version: Arch Linux
- Angular version: 13.3.3
- angular-cli version (or SystemJS/Webpack): 13.3.3
- I'm using Server Side Rendering with angular-universal: NO
- I'm compiling with mode: DEBUG

Browser:
- [x] Chrome (desktop) version Brave 1.37
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by Ks89** [comment]
Hi. Did you install angular/cdk as written in the  readme?

npm install --save hammerjs mousetrap @angular/cdk

**Comment by syrok0010** [comment]
Sure

**Comment by Ks89** [comment]
Do you have a runnable minimal example to prove this issue? I cannot reproduce it.

**Comment by syrok0010** [comment]
I cant reproduce it too

**Comment by Ks89** [comment]
Without a runnable code to reproduce this I can't do anything.
Did you try to remove node_modules and reinstall everything from scratch?

**Comment by syrok0010** [comment]
I see. I tried to remove node_modules and reinstall

**Comment by Ks89** [comment]
closed, because inactive
