### ISSUE TITLE
Circular dependency between ModalGalleryService and ModalGalleryComponent

### ISSUE THREAD

**Issue by StenCalDabran** [Ks89/angular-modal-gallery#261]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
The ModalGalleryComponent imports the ModalGalleryService and vice versa.
This circular dependency might lead to problems, in our case running tests (with Jest) no longer works.

## Expected behavior
No problems due to no circular dependency.

## Minimal reproduction of the problem with instructions
Execute `npx madge --circular --extensions ts ./` in Ks89/angular-modal-gallery will find exactly this one circular dependency.

If absolutely necessary I can build a repository that showcases the error, generally any repository testing with Jest will run into this problem. 

## What is the motivation / use case for changing the behavior?
Make tests work again (and potentially solve other problems where webpack/tree-shaking does not solve the circular dependency).

It looks like the only reason the `ModalGalleryComponent` is imported into the `ModalGalleryService` is to attach the `ModalGalleryComponent` to the overlay. This does not change the `ModalGalleryService` state at all and therefore could easily be done in a second service importing both `ModalGalleryService` and `ModalGalleryComponent`. The second service could then listen to some event-emitter from the `ModalGalleryService` to attach the component to the overly.
## Environment (the most important section to fill very carefully)

<pre><code>
- @ks89/angular-modal-gallery version: latest
</code></pre>

**Comment by Ks89** [comment]
Hi @StenCalDabran,
yes you are right about the circular dependency.
Do you want to create a small Pull Request with a possibile solution with the idea you proposed? I'm always open to improvements and fixes.

**Comment by StenCalDabran** [comment]
Thanks for the quick reply, I will work on a PR tomorrow.
