### ISSUE TITLE
ks89GalleryService.open() stopped working after update from 11.1.0 to 11.1.1

### ISSUE THREAD

**Issue by yarozar** [Ks89/angular-modal-gallery#266]
Do not have much time to test more thoroughly now to find more details but after today's library update for my project from v11.1.0 to the latest v11.1.1, service call `ks89GalleryService.open()` just stopped opening modal gallery. No errors, just nothing.

Decided to let you know ASAP as have noticed that update was rolled out like 2 weeks ago.

**Comment by Ks89** [comment]
Please could you provide the info required in the issue template? I cannot riproduce this issue, so I need every possibile detail about you env and use case.

**Comment by Ks89** [comment]
Ok perfect.
I close the issue
