### ISSUE TITLE
configChange in ngOnChanges always undefined

### ISSUE THREAD

**Issue by Dea1100** [Ks89/angular-modal-gallery#268]
https://github.com/Ks89/angular-modal-gallery/blob/d89367427b3f5870fd0a80f8780f40798c293d72/projects/ks89/angular-modal-gallery/src/lib/components/plain-gallery/plain-gallery.component.ts#L158

During debugging I noticed that the configChange in ngOnChanges will always be undefined since the correct way to access it would be "changes.config" and not "changes.plainGalleryConfig" (because the parameter is called "config" and not "plainGalleryConfig")

**Comment by Ks89** [comment]
Hi, I'll investigate because I totally forgot the reason of that check. Give me some days 😁

**Comment by Ks89** [comment]
You are right, it's bug.
It's incredible that no one found this previously :) Good catch!

I pushed v11.1.2
