### ISSUE TITLE
Rollup failure

### ISSUE THREAD

**Issue by patrickmichalina** [Ks89/angular-modal-gallery#56]
When using rollup: `'ModalGalleryModule' is not exported by node_modules/angular-modal-gallery/dist/bundles/angular-modal-gallery.umd.js`

**Comment by Ks89** [comment]
Hi. What does it mean for 'when using rollup'? Are you using angular in a project with rollup instead of either angular-cli or webpack? 

At the moment, I'm supporting only systemjs, angular-cli and webpack 2 but I'm really happy to add also rollup. To do that, I really need a demo project or something like that on github to test this library. 

Could you provide me more information about your scenario?

**Comment by Ks89** [comment]
Is this still an issue? Could you provide me more info? Did you create an example project for that?

Thank u.

**Comment by patrickmichalina** [comment]
You can close this! I do not use angular-cli, but moving on to fusebox so don't waste the effort. Thanks though

**Comment by Ks89** [comment]
Ok thank you for your response. 

However, I'll reopen the issue, because I want to investigate in the future.

**Comment by patrickmichalina** [comment]
Here is the seed I was using:

https://github.com/mgechev/angular-seed

install your module using SystemJS and then when running `npm run serve.prod.rollup.aot `. It failed during rollup

**Comment by Ks89** [comment]
ok I will try

**Comment by Ks89** [comment]
@patrickmichalina I'm trying to add my library to angular-seed without success.
How could you add this lib to that project? I used this tutorial https://github.com/mgechev/angular-seed/wiki/Add-external-dependency without success.

Do you have a working repo based on angular-seed with my library?

I can compile without errors, but when I try to run the app I get:
```
localhost/:62 SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502042965138:2821:16)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502042965138:3620:21
    at dynamicExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502042965138:1144:26)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502042965138:1091:13)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502042965138:999:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1502042965138:1017:20
    at Object.eval (http://localhost:5555/app/app.module.js:18:1)
    at eval (http://localhost:5555/app/app.module.js:43:4)
    at eval (http://localhost:5555/app/app.module.js:44:3) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
(anonymous) @ (index):62
```

I suppose that I'm doing something wrong or the official tutorial of angular-seed is wrong.

**Comment by Ks89** [comment]
angular-seed is now officially supported.

Please use angular-modal-gallery 4.0.0 or greater and check this demo project `https://github.com/Ks89/angular-seed-demo-with-angular-modal-gallery`
