### ISSUE TITLE
Angular CLI build error

### ISSUE THREAD

**Issue by krasznaidavid** [Ks89/angular-modal-gallery#77]
I'm getting the following error when building the project:

`ERROR in Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol KEYBOARD_CONFIGURATION in ...node_modules/angular-modal-gallery/src/modal-gallery.module.ts, resolving symbol ModalGalleryModule.forRoot

**Comment by Ks89** [comment]
This is related to #73 

Which template/starter/seed/skeleton are you using for your application?

**Comment by krasznaidavid** [comment]
It is a plain angular-cli project.

**Comment by Ks89** [comment]
Is it an open source project that I can try to build? 

PS angular-cli is officially supported by this project, in fact I provide an official example here https://github.com/Ks89/angular-modal-gallery/tree/master/demo/angular-cli
Did you try to compare your project with the official example? Did you try to download and build my example?

This is to be sure to isolate the problem. 

However the first thing that I suggest is this prpcedure:
- remove node_modules
- remove your package-lock.json (if existing) 
- npm clean verify (if I remember correctly the syntax of this command) 
- npm install (to reinstall again everything)

**Comment by Ks89** [comment]
Also try with a mom cache clean. 

If needed use also - - force

**Comment by krasznaidavid** [comment]
Thanks for your help! I was able to build the project.
