### ISSUE TITLE
Issue with import ModalGalleryModule

### ISSUE THREAD

**Issue by alhazmy13** [Ks89/angular-modal-gallery#89]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

When i try to import  `ModalGalleryModule.forRoot()` i got this error:
`ERROR in Error: Error encountered resolving symbol values statically. Calling function 'ModalGalleryModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in xxxxx`

**Comment by Ks89** [comment]
Hi. Which skeleton/template/starter are you using?
Are you using npm or yarn and which versions?

**Comment by alhazmy13** [comment]
> Which skeleton/template/starter are you using?

Angular CLI

> Are you using npm or yarn and which versions?

npm

**Comment by Ks89** [comment]
Could you try with my official example here https://github.com/Ks89/angular-modal-gallery/tree/master/demo/angular-cli ?

Is this issue still present also with my example?

**Comment by alhazmy13** [comment]
Weird, your example works fine, so I just stash everything on my project and then install it again.

And yeah it works fine, sorry for interrupting you.

**Comment by Ks89** [comment]
No problem man. I'm glad to help you
