### ISSUE TITLE
Thumbnail size/more options [Feature request]

### ISSUE THREAD

**Issue by Enngage** [Ks89/angular-modal-gallery#91]
[ ] Feature request

Be able to easily specify height of thumbnails

## What is the motivation / use case for changing the behavior?

Currently I had to specify a global style with `!important` flag in order to resize the thumbnails. I was trying all various ways, but only this one seems to work.

You could potentially extend the `Image `class with the thumbnail dimensions/size or have a new configuration option for the gallery as a whole. 

Having more options for the `Image` class with additional thumbnail properties would be also suitable for [this](https://github.com/Ks89/angular-modal-gallery/issues/76) as well. Maybe you can add a new `Thumbnail `class for this purpose.

**Comment by Ks89** [comment]
That's a good idea. I like it. Yes it is related to #76 

I schedule this issue for 4.0.0, so #80

**Comment by Enngage** [comment]
Cool, thanks for the quick response :-)

**Comment by matiishyn** [comment]
I have something similar.
I'd like to use my own components as thumbnails, clicking on which should open image-gallery
![image](https://user-images.githubusercontent.com/3661065/33710297-c953d5fa-db48-11e7-8034-326b0161fb8d.png)
Using `Angular 5.1` and `angular-image-gallery 5.0.0-alpha.2`

@Ks89 if it's possible, please give me the direction where to look for it. And thanks for your great work!

**Comment by Ks89** [comment]
With 5.0.0-alpha.2 is not possibile. However I'll give you a way to use custom thumbs.

At the moment I'm writing a component to show thumbs in different ways.
Obviously this is not ready and I'll need at least a month to implement eveything.

**Comment by Ks89** [comment]
Implemented and it will be released at the end of December with angular-modal-gallery 5.0.0 alpha 4.

It will be a basic implementation to add custom images specifying some properties like: tag to use to show the image (`<img>` or `<a>`), size, and other properties to enable 'image pointer' feature.
As always, I'll be very open about API (name, properties and so on).

PS: I think that I should change the main Image object to implement the idea of @Enngage , since this library it still in alpha stage.
What I though is something like this:

Image:{
  ... some common props like id, description and so on ...
  plain: { img, size ...},
  modal: {img, size....}
}

This is only an idea and I need some time to do this big refactor.

**Comment by Ks89** [comment]
```
Image:{
... some common props like id, description and so on ...
plain: { img, size ...},
modal: {img, size....}
}
```

implemented on the v4 branch 👍

**Comment by ckelkar** [comment]
Hello, I am trying to change thumbnail size by overriding .ng-thumb class as 
.ng-thumb{
  height: 100px;
  float: left;
  display: block;
  cursor: pointer;
  margin: 4px 4px 0 0;
}. 

I have created .scss file as shown. 

.more and .list-img are getting applied but not the above one. Can you please tell me what is the issue?

**Comment by Ks89** [comment]
Hi. 
Which version of angular modal gallery are you using?

**Comment by ckelkar** [comment]
Hi,
I am using angular-modal-gallery 5.6.0

**Comment by Ks89** [comment]
I'm sorry, but 5.6.0 doesn't exist. :)

The last stable version is 4.0.1 and the last beta version is 5.0.0-beta.1

**Comment by ckelkar** [comment]
Sorry, my bad. Manual error. I checked my package.json. it's 4.0.1.

**Comment by Ks89** [comment]
This feature is not supported in angular-modal-gallery 4.x.x.
At the end of February, I'll release 5.0.0 final with this, please be patient. However, it's already available in beta 1 (APIs are quite stable, so you can use it right now).
If you want a preview, check here: https://stackblitz.com/edit/angular-modal-gallery-v5 (see example 'Z1').
